# Generated by Django 5.2.3 on 2025-07-11 18:52

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when the record was created.', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the record was last updated.', verbose_name='updated at')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this record should be treated as active.', verbose_name='is active')),
                ('name', models.CharField(help_text='Name for this invoice template', max_length=100, verbose_name='template name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('default_payment_method', models.CharField(blank=True, max_length=50, verbose_name='default payment method')),
                ('default_payment_terms', models.CharField(blank=True, help_text='Default payment terms text', max_length=100, verbose_name='default payment terms')),
                ('additional_fields', models.JSONField(blank=True, default=dict, help_text='Additional fields to include in invoices', verbose_name='additional fields')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_templates', to='companies.company', verbose_name='company')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='updated by')),
            ],
            options={
                'verbose_name': 'Invoice Template',
                'verbose_name_plural': 'Invoice Templates',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when the record was created.', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the record was last updated.', verbose_name='updated at')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this record should be treated as active.', verbose_name='is active')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_categories', to='companies.company', verbose_name='company')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='invoicing.productcategory', verbose_name='parent category')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='updated by')),
            ],
            options={
                'verbose_name': 'Product Category',
                'verbose_name_plural': 'Product Categories',
                'ordering': ['name'],
                'unique_together': {('company', 'name')},
            },
        ),
        migrations.CreateModel(
            name='ProductTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when the record was created.', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the record was last updated.', verbose_name='updated at')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this record should be treated as active.', verbose_name='is active')),
                ('product_type', models.CharField(choices=[('PRODUCT', 'Product'), ('SERVICE', 'Service')], default='PRODUCT', max_length=20, verbose_name='product type')),
                ('main_code', models.CharField(help_text='Product main identification code', max_length=25, verbose_name='main code')),
                ('auxiliary_code', models.CharField(blank=True, help_text='Product auxiliary code', max_length=25, verbose_name='auxiliary code')),
                ('name', models.CharField(help_text='Product or service name', max_length=200, verbose_name='name')),
                ('description', models.TextField(help_text='Detailed product description', verbose_name='description')),
                ('unit_of_measure', models.CharField(default='u', help_text='Unit of measure (u, kg, m, etc.)', max_length=20, verbose_name='unit of measure')),
                ('unit_price', models.DecimalField(decimal_places=6, help_text='Default unit price', max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='unit price')),
                ('tax_rate', models.DecimalField(decimal_places=2, default=12.0, help_text='Default tax rate percentage', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='tax rate')),
                ('tax_code', models.CharField(choices=[('2', 'IVA'), ('3', 'ICE'), ('5', 'IRBPNR')], default='2', help_text='Tax type code', max_length=2, verbose_name='tax code')),
                ('track_inventory', models.BooleanField(default=False, help_text='Whether to track inventory for this product', verbose_name='track inventory')),
                ('current_stock', models.DecimalField(decimal_places=6, default=0, help_text='Current stock quantity', max_digits=12, verbose_name='current stock')),
                ('minimum_stock', models.DecimalField(decimal_places=6, default=0, help_text='Minimum stock level for alerts', max_digits=12, verbose_name='minimum stock')),
                ('additional_details', models.JSONField(blank=True, default=dict, help_text='Additional product details', verbose_name='additional details')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='invoicing.productcategory', verbose_name='category')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_templates', to='companies.company', verbose_name='company')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='updated by')),
            ],
            options={
                'verbose_name': 'Product Template',
                'verbose_name_plural': 'Product Templates',
                'ordering': ['name'],
                'unique_together': {('company', 'main_code')},
            },
        ),
        migrations.CreateModel(
            name='TemplateProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when the record was created.', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the record was last updated.', verbose_name='updated at')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this record should be treated as active.', verbose_name='is active')),
                ('default_quantity', models.DecimalField(decimal_places=6, default=1, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='default quantity')),
                ('default_discount', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='default discount')),
                ('order', models.PositiveIntegerField(default=0, help_text='Order of appearance in the template', verbose_name='order')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='template_uses', to='invoicing.producttemplate')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='template_products', to='invoicing.invoicetemplate')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='updated by')),
            ],
            options={
                'verbose_name': 'Template Product',
                'verbose_name_plural': 'Template Products',
                'ordering': ['order', 'product__name'],
                'unique_together': {('template', 'product')},
            },
        ),
        migrations.AddField(
            model_name='invoicetemplate',
            name='default_products',
            field=models.ManyToManyField(blank=True, related_name='invoice_templates', through='invoicing.TemplateProduct', to='invoicing.producttemplate'),
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when the record was created.', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the record was last updated.', verbose_name='updated at')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this record should be treated as active.', verbose_name='is active')),
                ('identification_type', models.CharField(choices=[('04', 'RUC'), ('05', 'Cedula'), ('06', 'Passport'), ('07', 'Consumer'), ('08', 'Foreign ID')], default='05', max_length=2, verbose_name='identification type')),
                ('identification', models.CharField(help_text='Customer identification number', max_length=20, verbose_name='identification')),
                ('name', models.CharField(help_text='Customer full name or business name', max_length=300, verbose_name='name')),
                ('email', models.EmailField(blank=True, help_text='Customer email address', max_length=254, verbose_name='email')),
                ('phone', models.CharField(blank=True, help_text='Customer phone number', max_length=20, verbose_name='phone')),
                ('address', models.TextField(blank=True, help_text='Customer address', verbose_name='address')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='city')),
                ('province', models.CharField(blank=True, max_length=100, verbose_name='province')),
                ('postal_code', models.CharField(blank=True, max_length=10, verbose_name='postal code')),
                ('default_payment_method', models.CharField(blank=True, help_text='Default payment method for this customer', max_length=50, verbose_name='default payment method')),
                ('credit_limit', models.DecimalField(decimal_places=2, default=0, help_text='Credit limit for this customer', max_digits=12, verbose_name='credit limit')),
                ('notes', models.TextField(blank=True, help_text='Additional notes about the customer', verbose_name='notes')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='companies.company', verbose_name='company')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='updated by')),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customers',
                'ordering': ['name'],
                'unique_together': {('company', 'identification')},
            },
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when the record was created.', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the record was last updated.', verbose_name='updated at')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this record should be treated as active.', verbose_name='is active')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('code', models.CharField(help_text='Internal code for this payment method', max_length=20, verbose_name='code')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('requires_bank_info', models.BooleanField(default=False, help_text='Whether this payment method requires bank information', verbose_name='requires bank info')),
                ('default_days_to_pay', models.PositiveIntegerField(default=0, help_text='Default number of days for payment', verbose_name='default days to pay')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_methods', to='companies.company', verbose_name='company')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='updated by')),
            ],
            options={
                'verbose_name': 'Payment Method',
                'verbose_name_plural': 'Payment Methods',
                'ordering': ['name'],
                'unique_together': {('company', 'code')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='invoicetemplate',
            unique_together={('company', 'name')},
        ),
    ]
