# Generated by Django 6.0.3 on 2026-04-23 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producttemplate',
            name='description',
            field=models.TextField(blank=True, help_text='Detailed product description', verbose_name='description'),
        ),
    ]
