# Generated by Django 6.0.3 on 2026-04-23 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_stockmovement'),
        ('invoicing', '0002_alter_producttemplate_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='producttemplate',
            name='image',
            field=models.ImageField(blank=True, help_text='Product image', null=True, upload_to='products/', verbose_name='image'),
        ),
        migrations.AddField(
            model_name='producttemplate',
            name='main_provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='inventory.provider', verbose_name='main provider'),
        ),
    ]
