# Generated by Django 6.0.3 on 2026-04-27 14:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0003_producttemplate_image_producttemplate_main_provider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producttemplate',
            name='tax_rate',
            field=models.DecimalField(decimal_places=2, default=15.0, help_text='Default tax rate percentage', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='tax rate'),
        ),
    ]
