# Generated by Django 5.2.13 on 2026-05-03 20:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0005_customer_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when the record was created.', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the record was last updated.', verbose_name='updated at')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this record should be treated as active.', verbose_name='is active')),
                ('name', models.CharField(help_text='Ej: Mi Casa, Oficina, Trabajo', max_length=100, verbose_name='name')),
                ('address', models.TextField(verbose_name='address')),
                ('reference', models.TextField(blank=True, help_text='Barrio, color de casa, etc.', verbose_name='reference')),
                ('is_default', models.BooleanField(default=False, verbose_name='is default')),
                ('latitude', models.DecimalField(blank=True, decimal_places=9, max_digits=12, null=True, verbose_name='latitude')),
                ('longitude', models.DecimalField(blank=True, decimal_places=9, max_digits=12, null=True, verbose_name='longitude')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='invoicing.customer', verbose_name='customer')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='updated by')),
            ],
            options={
                'verbose_name': 'Customer Address',
                'verbose_name_plural': 'Customer Addresses',
                'ordering': ['-is_default', '-created_at'],
            },
        ),
    ]
