# Generated by Django 6.0.3 on 2026-05-03 23:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0006_customeraddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='producttemplate',
            name='purchase_price',
            field=models.DecimalField(decimal_places=6, default=0, help_text='Base purchase cost', max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='purchase price'),
        ),
        migrations.AlterField(
            model_name='producttemplate',
            name='unit_price',
            field=models.DecimalField(decimal_places=6, help_text='Default selling price', max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='unit price'),
        ),
    ]
