# Generated by Django 6.0.3 on 2026-04-23 02:31

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0006_company_regimen'),
        ('invoicing', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when the record was created.', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the record was last updated.', verbose_name='updated at')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this record should be treated as active.', verbose_name='is active')),
                ('identification_type', models.CharField(choices=[('04', 'RUC'), ('05', 'Cédula'), ('06', 'Pasaporte'), ('08', 'Identificación del Exterior')], default='04', max_length=2, verbose_name='identification type')),
                ('identification', models.CharField(help_text='Provider RUC or ID', max_length=20, verbose_name='identification')),
                ('name', models.CharField(help_text='Provider business name', max_length=300, verbose_name='name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='phone')),
                ('address', models.TextField(blank=True, verbose_name='address')),
                ('regime', models.CharField(choices=[('GENERAL', 'Régimen General'), ('RIMPE_EMPRENDEDOR', 'Régimen RIMPE - Emprendedor'), ('RIMPE_POPULAR', 'Régimen RIMPE - Negocio Popular'), ('AGROPECUARIO', 'Régimen Agropecuario')], default='GENERAL', max_length=30, verbose_name='regime')),
                ('provider_code', models.CharField(blank=True, help_text='Internal code or key for the provider', max_length=50, verbose_name='provider code')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='providers', to='companies.company', verbose_name='company')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='updated by')),
            ],
            options={
                'verbose_name': 'Provider',
                'verbose_name_plural': 'Providers',
                'ordering': ['name'],
                'unique_together': {('company', 'identification')},
            },
        ),
        migrations.CreateModel(
            name='PurchaseInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when the record was created.', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the record was last updated.', verbose_name='updated at')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this record should be treated as active.', verbose_name='is active')),
                ('invoice_number', models.CharField(help_text='Format: 001-001-000000001', max_length=50, verbose_name='invoice number')),
                ('issue_date', models.DateField(verbose_name='issue date')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='total amount')),
                ('notes', models.TextField(blank=True)),
                ('is_processed', models.BooleanField(default=False, help_text='True if inventory has been updated', verbose_name='is processed')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_invoices', to='companies.company')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='inventory.provider')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='updated by')),
            ],
            options={
                'verbose_name': 'Purchase Invoice',
                'verbose_name_plural': 'Purchase Invoices',
                'ordering': ['-issue_date'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when the record was created.', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the record was last updated.', verbose_name='updated at')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this record should be treated as active.', verbose_name='is active')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='quantity')),
                ('cost_price', models.DecimalField(decimal_places=6, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='cost price')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='subtotal')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_items', to='invoicing.producttemplate')),
                ('purchase_invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.purchaseinvoice')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='updated by')),
            ],
            options={
                'verbose_name': 'Purchase Item',
                'verbose_name_plural': 'Purchase Items',
            },
        ),
    ]
