# Generated by Django 6.0.3 on 2026-04-23 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='authorization_number',
            field=models.CharField(blank=True, help_text='SRI Authorization number for physical invoices', max_length=50, verbose_name='authorization number'),
        ),
        migrations.AddField(
            model_name='provider',
            name='end_sequence',
            field=models.PositiveIntegerField(blank=True, help_text='Ending invoice number authorized', null=True, verbose_name='end sequence'),
        ),
        migrations.AddField(
            model_name='provider',
            name='expiration_date',
            field=models.DateField(blank=True, help_text='Expiration date of the SRI authorization', null=True, verbose_name='expiration date'),
        ),
        migrations.AddField(
            model_name='provider',
            name='start_sequence',
            field=models.PositiveIntegerField(blank=True, help_text='Starting invoice number authorized', null=True, verbose_name='start sequence'),
        ),
    ]
