# Generated by Django 6.0.3 on 2026-04-23 00:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0006_company_regimen'),
        ('tracking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackingroute',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tracking_routes', to='companies.company'),
        ),
    ]
