# Generated by Django 6.0.3 on 2026-05-02 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='destination_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='destination name'),
        ),
        migrations.AddField(
            model_name='route',
            name='google_maps_url',
            field=models.URLField(blank=True, max_length=500, verbose_name='google maps url'),
        ),
    ]
