# Generated by Django 5.2.13 on 2026-05-02 16:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0005_customer_user'),
        ('logistics', '0003_alter_route_vehicle_routetemplate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RouteProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when the record was created.', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the record was last updated.', verbose_name='updated at')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this record should be treated as active.', verbose_name='is active')),
                ('quantity_loaded', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='quantity loaded')),
                ('quantity_sold', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='quantity sold')),
                ('quantity_returned', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='quantity returned')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_assignments', to='invoicing.producttemplate')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='logistics.route')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='updated by')),
            ],
            options={
                'verbose_name': 'Route Product',
                'verbose_name_plural': 'Route Products',
            },
        ),
    ]
