# Generated by Django 5.2.13 on 2026-05-03 18:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0006_routedelivery_seller'),
        ('sri_integration', '0012_documentitem_credit_note_documenttax_credit_note_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='routedelivery',
            name='invoice',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='route_delivery', to='sri_integration.electronicdocument', verbose_name='invoice'),
        ),
        migrations.AddField(
            model_name='routedelivery',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=9, max_digits=12, null=True, verbose_name='latitude'),
        ),
        migrations.AddField(
            model_name='routedelivery',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=9, max_digits=12, null=True, verbose_name='longitude'),
        ),
    ]
