# Generated by Django 5.2.3 on 2025-07-11 18:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when the record was created.', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the record was last updated.', verbose_name='updated at')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this record should be treated as active.', verbose_name='is active')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('message', models.TextField(verbose_name='message')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SENT', 'Sent'), ('DELIVERED', 'Delivered'), ('READ', 'Read'), ('FAILED', 'Failed')], default='PENDING', max_length=20, verbose_name='status')),
                ('scheduled_for', models.DateTimeField(blank=True, help_text='When to send this notification', null=True, verbose_name='scheduled for')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='sent at')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='read at')),
                ('context_data', models.JSONField(blank=True, default=dict, help_text='Additional data related to this notification', verbose_name='context data')),
                ('sent_via_email', models.BooleanField(default=False, verbose_name='sent via email')),
                ('sent_via_browser', models.BooleanField(default=False, verbose_name='sent via browser')),
                ('sent_via_sms', models.BooleanField(default=False, verbose_name='sent via SMS')),
                ('sent_via_webhook', models.BooleanField(default=False, verbose_name='sent via webhook')),
                ('action_url', models.URLField(blank=True, help_text='URL to redirect when notification is clicked', verbose_name='action URL')),
                ('action_text', models.CharField(blank=True, help_text='Text for the action button', max_length=50, verbose_name='action text')),
                ('delivery_attempts', models.PositiveIntegerField(default=0, verbose_name='delivery attempts')),
                ('last_attempt_at', models.DateTimeField(blank=True, null=True, verbose_name='last attempt at')),
                ('error_message', models.TextField(blank=True, help_text='Error message if delivery failed', verbose_name='error message')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='companies.company', verbose_name='company')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications_received', to=settings.AUTH_USER_MODEL, verbose_name='recipient')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='updated by')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when the record was created.', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the record was last updated.', verbose_name='updated at')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this record should be treated as active.', verbose_name='is active')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='channel name')),
                ('channel_type', models.CharField(choices=[('EMAIL', 'Email'), ('SMS', 'SMS'), ('WEBHOOK', 'Webhook'), ('SLACK', 'Slack'), ('TELEGRAM', 'Telegram')], max_length=20, verbose_name='channel type')),
                ('configuration', models.JSONField(default=dict, help_text='Channel-specific configuration (API keys, URLs, etc.)', verbose_name='configuration')),
                ('enabled', models.BooleanField(default=True, verbose_name='enabled')),
                ('rate_limit_per_minute', models.PositiveIntegerField(default=60, help_text='Maximum notifications per minute', verbose_name='rate limit per minute')),
                ('rate_limit_per_hour', models.PositiveIntegerField(default=1000, help_text='Maximum notifications per hour', verbose_name='rate limit per hour')),
                ('total_sent', models.PositiveIntegerField(default=0, verbose_name='total sent')),
                ('total_failed', models.PositiveIntegerField(default=0, verbose_name='total failed')),
                ('last_used_at', models.DateTimeField(blank=True, null=True, verbose_name='last used at')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='updated by')),
            ],
            options={
                'verbose_name': 'Notification Channel',
                'verbose_name_plural': 'Notification Channels',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when the record was created.', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the record was last updated.', verbose_name='updated at')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this record should be treated as active.', verbose_name='is active')),
                ('success', models.BooleanField(default=False, verbose_name='success')),
                ('response_code', models.CharField(blank=True, max_length=10, verbose_name='response code')),
                ('response_message', models.TextField(blank=True, verbose_name='response message')),
                ('sent_at', models.DateTimeField(auto_now_add=True, verbose_name='sent at')),
                ('delivery_time_ms', models.PositiveIntegerField(blank=True, help_text='Time taken to deliver notification in milliseconds', null=True, verbose_name='delivery time (ms)')),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='notifications.notificationchannel', verbose_name='channel')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='notifications.notification', verbose_name='notification')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='updated by')),
            ],
            options={
                'verbose_name': 'Notification Log',
                'verbose_name_plural': 'Notification Logs',
                'ordering': ['-sent_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when the record was created.', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the record was last updated.', verbose_name='updated at')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this record should be treated as active.', verbose_name='is active')),
                ('notification_type', models.CharField(choices=[('DOCUMENT_AUTHORIZED', 'Document Authorized'), ('DOCUMENT_REJECTED', 'Document Rejected'), ('CERTIFICATE_EXPIRING', 'Certificate Expiring'), ('CERTIFICATE_EXPIRED', 'Certificate Expired'), ('BACKUP_COMPLETED', 'Backup Completed'), ('BACKUP_FAILED', 'Backup Failed'), ('SYSTEM_ERROR', 'System Error'), ('LOW_STOCK', 'Low Stock'), ('PAYMENT_REMINDER', 'Payment Reminder'), ('WELCOME', 'Welcome'), ('PASSWORD_CHANGED', 'Password Changed'), ('LOGIN_ALERT', 'Login Alert')], max_length=30, unique=True, verbose_name='notification type')),
                ('name', models.CharField(max_length=100, verbose_name='template name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('email_enabled', models.BooleanField(default=True, verbose_name='email enabled')),
                ('browser_enabled', models.BooleanField(default=True, verbose_name='browser enabled')),
                ('sms_enabled', models.BooleanField(default=False, verbose_name='SMS enabled')),
                ('webhook_enabled', models.BooleanField(default=False, verbose_name='webhook enabled')),
                ('email_subject', models.CharField(blank=True, help_text='Email subject template with variables like {variable}', max_length=255, verbose_name='email subject')),
                ('email_template', models.TextField(blank=True, help_text='Email body template with variables', verbose_name='email template')),
                ('browser_title', models.CharField(blank=True, max_length=100, verbose_name='browser notification title')),
                ('browser_message', models.TextField(blank=True, verbose_name='browser notification message')),
                ('sms_message', models.CharField(blank=True, help_text='SMS message template (max 160 chars)', max_length=160, verbose_name='SMS message')),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('NORMAL', 'Normal'), ('HIGH', 'High'), ('URGENT', 'Urgent')], default='NORMAL', max_length=10, verbose_name='priority')),
                ('delay_minutes', models.PositiveIntegerField(default=0, help_text='Minutes to wait before sending notification', verbose_name='delay in minutes')),
                ('retry_attempts', models.PositiveIntegerField(default=3, help_text='Number of retry attempts for failed notifications', verbose_name='retry attempts')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='updated by')),
            ],
            options={
                'verbose_name': 'Notification Template',
                'verbose_name_plural': 'Notification Templates',
                'ordering': ['notification_type'],
            },
        ),
        migrations.AddField(
            model_name='notification',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='notifications.notificationtemplate', verbose_name='template'),
        ),
        migrations.CreateModel(
            name='NotificationSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when the record was created.', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the record was last updated.', verbose_name='updated at')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this record should be treated as active.', verbose_name='is active')),
                ('notification_type', models.CharField(choices=[('DOCUMENT_AUTHORIZED', 'Document Authorized'), ('DOCUMENT_REJECTED', 'Document Rejected'), ('CERTIFICATE_EXPIRING', 'Certificate Expiring'), ('CERTIFICATE_EXPIRED', 'Certificate Expired'), ('BACKUP_COMPLETED', 'Backup Completed'), ('BACKUP_FAILED', 'Backup Failed'), ('SYSTEM_ERROR', 'System Error'), ('LOW_STOCK', 'Low Stock'), ('PAYMENT_REMINDER', 'Payment Reminder'), ('WELCOME', 'Welcome'), ('PASSWORD_CHANGED', 'Password Changed'), ('LOGIN_ALERT', 'Login Alert')], max_length=30, verbose_name='notification type')),
                ('email_enabled', models.BooleanField(default=True, verbose_name='email enabled')),
                ('browser_enabled', models.BooleanField(default=True, verbose_name='browser enabled')),
                ('sms_enabled', models.BooleanField(default=False, verbose_name='SMS enabled')),
                ('frequency', models.CharField(choices=[('IMMEDIATE', 'Immediate'), ('HOURLY', 'Hourly'), ('DAILY', 'Daily'), ('WEEKLY', 'Weekly')], default='IMMEDIATE', max_length=20, verbose_name='frequency')),
                ('quiet_hours_start', models.TimeField(blank=True, help_text='Start of quiet hours (no notifications)', null=True, verbose_name='quiet hours start')),
                ('quiet_hours_end', models.TimeField(blank=True, help_text='End of quiet hours', null=True, verbose_name='quiet hours end')),
                ('company', models.ForeignKey(blank=True, help_text='Company-specific subscription (leave empty for global)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notification_subscriptions', to='companies.company', verbose_name='company')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='updated by')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_subscriptions', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'Notification Subscription',
                'verbose_name_plural': 'Notification Subscriptions',
                'ordering': ['user', 'notification_type'],
                'unique_together': {('user', 'notification_type', 'company')},
            },
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient', 'status'], name='notificatio_recipie_e285de_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient', 'read_at'], name='notificatio_recipie_564b1f_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['company', 'created_at'], name='notificatio_company_c7a3fc_idx'),
        ),
    ]
