# -*- coding: utf-8 -*-
"""
Django settings for RutaFact_SRI project with OAuth support.
Sistema de Facturación SRI - Configuración con Autenticación OAuth
ACTUALIZADO con GlobalCertificateManager, Token Authentication y CELERY
CORREGIDO: Cache Redis con django-redis backend

Generated by 'django-admin startproject' using Django 5.2.3.
"""

from pathlib import Path
from decouple import config
import os
import sys

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# ==========================================
# SECURITY SETTINGS
# ==========================================

SECRET_KEY = config('SECRET_KEY', default='django-insecure-rutafact-sri-change-this-in-production')
DEBUG = config('DEBUG', default=True, cast=bool)

# Hosts permitidos - mejor gestión con .env
ALLOWED_HOSTS = config('ALLOWED_HOSTS', default='localhost,127.0.0.1,0.0.0.0,testserver').split(',')



CSRF_TRUSTED_ORIGINS = config('CSRF_TRUSTED_ORIGINS', default='https://localhost:8000').split(',')

# ==========================================
# APPLICATION DEFINITION
# ==========================================

# Django core apps
DJANGO_APPS = [
    'daphne',  # ✅ Requerido para Channels
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'django_celery_beat',
    'channels',  # ✅ Django Channels
]

# Third party apps
THIRD_PARTY_APPS = [
    # API
    'rest_framework',
    'rest_framework.authtoken',
    'corsheaders',
    'django_filters',
    
    # Forms (UI removida por migración a Flutter API)
    # 'crispy_forms',
    # 'crispy_bootstrap5',
    
    # OAuth & Authentication
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
]

# Local apps
LOCAL_APPS = [
    'apps.core',
    'apps.users',
    'apps.companies',
    'apps.certificates',
    'apps.invoicing',
    'apps.notifications',
    'apps.settings',
    'apps.sri_integration',
    'apps.api',
    'apps.billing',
    'apps.logistics',
    'apps.tracking',
]

INSTALLED_APPS = DJANGO_APPS + THIRD_PARTY_APPS + LOCAL_APPS

# ==========================================
# MIDDLEWARE CONFIGURATION
# ==========================================

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'allauth.account.middleware.AccountMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'apps.billing.middleware.BillingLimitMiddleware',
    'apps.users.views.SimpleSessionTimeoutMiddleware',
    'apps.users.views.CheckUserAccessMiddleware',
    'apps.api.permissions.CompanySecurityMiddleware',
    'apps.core.middleware.DashboardSecurityMiddleware',
]

ROOT_URLCONF = 'rutafact.urls'

# ==========================================
# SITES FRAMEWORK (REQUERIDO PARA ALLAUTH)
# ==========================================

SITE_ID = config('SITE_ID', default=1, cast=int)

# ==========================================
# AUTHENTICATION CONFIGURATION
# ==========================================

# Authentication backends
AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]

# URLs de autenticación
LOGIN_URL = config('LOGIN_URL', default='/accounts/login/')
LOGIN_REDIRECT_URL = config('LOGIN_REDIRECT_URL', default='/accounts/login/')
LOGOUT_REDIRECT_URL = config('LOGOUT_REDIRECT_URL', default='/accounts/login/')

# ==========================================
# ALLAUTH CONFIGURATION
# ==========================================

# Configuración de cuentas (Actualizado para evitar deprecaciones en allauth)
ACCOUNT_LOGIN_METHODS = {config('ACCOUNT_AUTHENTICATION_METHOD', default='email')}
ACCOUNT_EMAIL_VERIFICATION = config('ACCOUNT_EMAIL_VERIFICATION', default='optional')
ACCOUNT_SIGNUP_FIELDS = ['email*', 'password1*', 'password2*']
ACCOUNT_USER_MODEL_USERNAME_FIELD = None
ACCOUNT_USER_MODEL_EMAIL_FIELD = 'email'
ACCOUNT_UNIQUE_EMAIL = config('ACCOUNT_UNIQUE_EMAIL', default=True, cast=bool)
ACCOUNT_SESSION_REMEMBER = config('ACCOUNT_SESSION_REMEMBER', default=True, cast=bool)

# URLs personalizadas
ACCOUNT_LOGIN_URL = config('ACCOUNT_LOGIN_URL', default='/accounts/login/')
ACCOUNT_LOGOUT_URL = config('ACCOUNT_LOGOUT_URL', default='/accounts/logout/')
ACCOUNT_SIGNUP_URL = config('ACCOUNT_SIGNUP_URL', default='/accounts/signup/')

# Rate limiting
ACCOUNT_RATE_LIMITS = {
    'login_failed': config('ACCOUNT_LOGIN_FAILED_LIMIT', default='5/5m'),
    'signup': config('ACCOUNT_SIGNUP_LIMIT', default='20/h'),
}

# Configuración de cuentas sociales
SOCIALACCOUNT_AUTO_SIGNUP = config('SOCIALACCOUNT_AUTO_SIGNUP', default=True, cast=bool)
SOCIALACCOUNT_EMAIL_REQUIRED = config('SOCIALACCOUNT_EMAIL_REQUIRED', default=True, cast=bool)
SOCIALACCOUNT_EMAIL_VERIFICATION = config('SOCIALACCOUNT_EMAIL_VERIFICATION', default='optional')
SOCIALACCOUNT_EMAIL_AUTHENTICATION = config('SOCIALACCOUNT_EMAIL_AUTHENTICATION', default=True, cast=bool)
SOCIALACCOUNT_EMAIL_AUTHENTICATION_AUTO_CONNECT = config('SOCIALACCOUNT_EMAIL_AUTH_AUTO_CONNECT', default=True, cast=bool)
SOCIALACCOUNT_LOGIN_ON_GET = config('SOCIALACCOUNT_LOGIN_ON_GET', default=True, cast=bool)

# Providers de OAuth
SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'SCOPE': [
            'profile',
            'email',
        ],
        'AUTH_PARAMS': {
            'access_type': 'online',
        },
        'OAUTH_PKCE_ENABLED': config('GOOGLE_OAUTH_PKCE_ENABLED', default=True, cast=bool),
        'FETCH_USERINFO': config('GOOGLE_FETCH_USERINFO', default=True, cast=bool),
        'VERIFIED_EMAIL': config('GOOGLE_VERIFIED_EMAIL', default=True, cast=bool),
        'VERSION': config('GOOGLE_API_VERSION', default='v2'),
        'APP': {
            'client_id': config('GOOGLE_CLIENT_ID', default=''),
            'secret': config('GOOGLE_CLIENT_SECRET', default=''),
        }
    }
}

# ==========================================
# TEMPLATES CONFIGURATION
# ==========================================

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.i18n',
                'django.template.context_processors.media',
                'django.template.context_processors.static',
                'django.template.context_processors.tz',
                'apps.core.context_processors.system_branding',
            ],
        },
    },
]

WSGI_APPLICATION = 'rutafact.wsgi.application'
ASGI_APPLICATION = 'rutafact.asgi.application'

# ==========================================
# DATABASE CONFIGURATION
# ==========================================

DATABASES = {
    'default': {
        'ENGINE': config('DB_ENGINE', default='django.db.backends.postgresql'),
        'NAME': config('DB_NAME', default='rutafact'),
        'USER': config('DB_USER', default='postgres'),
        'PASSWORD': config('DB_PASSWORD', default='password'),
        'HOST': config('DB_HOST', default='localhost'),
        'PORT': config('DB_PORT', default='5432'),
        'OPTIONS': {
            'options': config('DB_OPTIONS', default='-c search_path=public'),
        },
    }
}

# ==========================================
# USER MODEL CONFIGURATION
# ==========================================

AUTH_USER_MODEL = 'users.User'

# 📍 Google Maps Config
GOOGLE_MAPS_API_KEY = config('GOOGLE_MAPS_API_KEY', default='')


# ==========================================
# PASSWORD VALIDATION
# ==========================================

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {
            'min_length': config('PASSWORD_MIN_LENGTH', default=8, cast=int),
        }
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# ==========================================
# INTERNATIONALIZATION
# ==========================================

LANGUAGE_CODE = config('LANGUAGE_CODE', default='es-ec')
TIME_ZONE = config('TIME_ZONE', default='America/Guayaquil')
USE_I18N = config('USE_I18N', default=True, cast=bool)
USE_TZ = config('USE_TZ', default=True, cast=bool)

# ==========================================
# STATIC FILES CONFIGURATION
# ==========================================

STATIC_URL = config('STATIC_URL', default='/static/')
STATIC_ROOT = BASE_DIR / config('STATIC_ROOT', default='staticfiles')

STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

# ==========================================
# MEDIA FILES CONFIGURATION
# ==========================================

MEDIA_URL = config('MEDIA_URL', default='/media/')
MEDIA_ROOT = os.path.join(BASE_DIR, config('MEDIA_ROOT', default='storage'))

# Configuración de Storage Local
STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
    },
}

# ==========================================
# DEFAULT AUTO FIELD
# ==========================================

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ==========================================
# REST FRAMEWORK CONFIGURATION CON TOKEN
# ==========================================

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework_simplejwt.authentication.JWTAuthentication",
        "apps.api.authentication.DualTokenAuthentication",
        "rest_framework.authentication.SessionAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ],
    "DEFAULT_RENDERER_CLASSES": [
        "rest_framework.renderers.JSONRenderer",
        "rest_framework.renderers.BrowsableAPIRenderer",
    ],
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": config('API_PAGE_SIZE', default=25, cast=int),
    "DEFAULT_FILTER_BACKENDS": [
        "django_filters.rest_framework.DjangoFilterBackend",
        "rest_framework.filters.SearchFilter",
        "rest_framework.filters.OrderingFilter",
    ],
    "DEFAULT_THROTTLE_CLASSES": [
        "rest_framework.throttling.AnonRateThrottle",
        "rest_framework.throttling.UserRateThrottle"
    ],
    "DEFAULT_THROTTLE_RATES": {
        "anon": config('API_THROTTLE_ANON', default='100/day'),
        "user": config('API_THROTTLE_USER', default='1000/day')
    }
}

# ==========================================
# JWT AUTHENTICATION SETTINGS
# ==========================================

from datetime import timedelta

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(days=2),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'AUTH_HEADER_TYPES': ('Bearer', 'Token'),
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
}

# ==========================================
# TOKEN AUTHENTICATION SETTINGS
# ==========================================

AUTO_CREATE_TOKENS = config('AUTO_CREATE_TOKENS', default=True, cast=bool)
TOKEN_EXPIRES = config('TOKEN_EXPIRES', default=None)
AUTO_REGENERATE_TOKEN_ON_LOGIN = config('AUTO_REGENERATE_TOKEN', default=False, cast=bool)

# ==========================================
# CORS CONFIGURATION
# ==========================================

# CORS origins desde .env
CORS_ALLOWED_ORIGINS = config('CORS_ALLOWED_ORIGINS', 
    default='http://localhost:3000,http://127.0.0.1:3000,http://localhost:8000,http://127.0.0.1:8000'
).split(',')

CORS_ALLOW_CREDENTIALS = config('CORS_ALLOW_CREDENTIALS', default=True, cast=bool)

# Headers permitidos para API calls con token
CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
    'x-api-key',
    'x-auth-token',
    'ngrok-skip-browser-warning',
]

# ==========================================
# CRISPY FORMS CONFIGURATION
# ==========================================

# CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"
# CRISPY_TEMPLATE_PACK = "bootstrap5"

# ==========================================
# MESSAGE TAGS FOR BOOTSTRAP
# ==========================================

from django.contrib.messages import constants as messages
MESSAGE_TAGS = {
    messages.DEBUG: 'debug',
    messages.INFO: 'info',
    messages.SUCCESS: 'success',
    messages.WARNING: 'warning',
    messages.ERROR: 'danger',
}

# ==========================================
# EMAIL CONFIGURATION
# ==========================================

# Email backend desde .env
EMAIL_BACKEND = config('EMAIL_BACKEND', default='django.core.mail.backends.console.EmailBackend')
EMAIL_HOST = config('EMAIL_HOST', default='smtp.gmail.com')
EMAIL_PORT = config('EMAIL_PORT', default=587, cast=int)
EMAIL_USE_TLS = config('EMAIL_USE_TLS', default=True, cast=bool)
EMAIL_USE_SSL = config('EMAIL_USE_SSL', default=False, cast=bool)
EMAIL_HOST_USER = config('EMAIL_HOST_USER', default='')
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD', default='')
DEFAULT_FROM_EMAIL = config('DEFAULT_FROM_EMAIL', default='noreply@rutafact-sri.com')

# ==========================================
# SRI CONFIGURATION
# ==========================================

SRI_AMBIENTE = config('SRI_AMBIENTE', default='1')  # 1=Pruebas, 2=Producción
SRI_TIPO_EMISION = config('SRI_TIPO_EMISION', default='1')  # 1=Normal
SRI_TIMEOUT = config('SRI_TIMEOUT', default=30, cast=int)

# URLs SRI según ambiente
SRI_URLS = {
    '1': {  # Pruebas
        'recepcion': config('SRI_TEST_RECEPCION_URL', 
            default='https://celcer.sri.gob.ec/comprobantes-electronicos-ws/RecepcionComprobantesOffline?wsdl'),
        'autorizacion': config('SRI_TEST_AUTORIZACION_URL',
            default='https://celcer.sri.gob.ec/comprobantes-electronicos-ws/AutorizacionComprobantesOffline?wsdl')
    },
    '2': {  # Producción
        'recepcion': config('SRI_PROD_RECEPCION_URL',
            default='https://cel.sri.gob.ec/comprobantes-electronicos-ws/RecepcionComprobantesOffline?wsdl'),
        'autorizacion': config('SRI_PROD_AUTORIZACION_URL',
            default='https://cel.sri.gob.ec/comprobantes-electronicos-ws/AutorizacionComprobantesOffline?wsdl')
    }
}

# Configuración de timeouts para SRI
SRI_TIMEOUTS = {
    'connection_timeout': config('SRI_CONNECTION_TIMEOUT', default=30, cast=int),
    'read_timeout': config('SRI_READ_TIMEOUT', default=60, cast=int),
    'authorization_max_attempts': config('SRI_AUTH_MAX_ATTEMPTS', default=10, cast=int),
    'authorization_wait_seconds': config('SRI_AUTH_WAIT_SECONDS', default=30, cast=int),
}

# URLs del SRI actualizadas con configuración de ambientes
SRI_URLS_COMPLETE = {
    'PRODUCTION': {
        'reception': config('SRI_PROD_RECEPCION_URL',
            default='https://cel.sri.gob.ec/comprobantes-electronicos-ws/RecepcionComprobantesOffline?wsdl'),
        'authorization': config('SRI_PROD_AUTORIZACION_URL',
            default='https://cel.sri.gob.ec/comprobantes-electronicos-ws/AutorizacionComprobantesOffline?wsdl'),
    },
    'TEST': {
        'reception': config('SRI_TEST_RECEPCION_URL',
            default='https://celcer.sri.gob.ec/comprobantes-electronicos-ws/RecepcionComprobantesOffline?wsdl'),
        'authorization': config('SRI_TEST_AUTORIZACION_URL',
            default='https://celcer.sri.gob.ec/comprobantes-electronicos-ws/AutorizacionComprobantesOffline?wsdl'),
    }
}

# ==========================================
# SESSION CONFIGURATION
# ==========================================

SESSION_COOKIE_AGE = config('SESSION_COOKIE_AGE', default=3600, cast=int)  # 1 hora
SESSION_EXPIRE_AT_BROWSER_CLOSE = config('SESSION_EXPIRE_AT_BROWSER_CLOSE', default=True, cast=bool)
SESSION_SAVE_EVERY_REQUEST = config('SESSION_SAVE_EVERY_REQUEST', default=True, cast=bool)
SESSION_COOKIE_NAME = config('SESSION_COOKIE_NAME', default='rutafact_sessionid')
SESSION_COOKIE_SECURE = config('SESSION_COOKIE_SECURE', default=not DEBUG, cast=bool)
SESSION_COOKIE_HTTPONLY = config('SESSION_COOKIE_HTTPONLY', default=True, cast=bool)
SESSION_COOKIE_SAMESITE = config('SESSION_COOKIE_SAMESITE', default='Lax')
SESSION_TIMEOUT_WARNING = config('SESSION_TIMEOUT_WARNING', default=300, cast=int)  # 5 minutos
SESSION_ENGINE = config('SESSION_ENGINE', default='django.contrib.sessions.backends.db')

# ==========================================
# REDIS CONFIGURATION - ✅ CORREGIDO PARA DOCKER
# ==========================================

# URLs de Redis desde .env - CORREGIDO para usar el nombre del servicio Docker
REDIS_HOST = config('REDIS_HOST', default='rutafact-redis')
REDIS_PORT = config('REDIS_PORT', default=6379, cast=int)
REDIS_DB = config('REDIS_DB', default=0, cast=int)
REDIS_PASSWORD = config('REDIS_PASSWORD', default='Redis2026Secure!')
REDIS_AUTH = f":{REDIS_PASSWORD}@" if REDIS_PASSWORD else ""

# Construir URL de Redis automáticamente - ✅ CORREGIDO
REDIS_URL = config('REDIS_URL', default=f'redis://{REDIS_HOST}:{REDIS_PORT}')

# ==========================================
# CHANNEL LAYERS CONFIGURATION - ✅ AGREGADO
# ==========================================
CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels_redis.core.RedisChannelLayer',
        'CONFIG': {
            "hosts": [f'redis://{REDIS_AUTH}{REDIS_HOST}:{REDIS_PORT}'],
        },
    },
}

# ==========================================
# CELERY CONFIGURATION - ✅ COMPLETAMENTE CORREGIDO
# ==========================================

# ✅ Configuración principal de Celery CORREGIDA para Docker
CELERY_BROKER_URL = config('CELERY_BROKER_URL', default=f'redis://{REDIS_AUTH}{REDIS_HOST}:{REDIS_PORT}/0')
CELERY_RESULT_BACKEND = config('CELERY_RESULT_BACKEND', default=f'redis://{REDIS_AUTH}{REDIS_HOST}:{REDIS_PORT}/1')

# Configuración de serialización
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = TIME_ZONE

# Configuración de workers
CELERY_WORKER_PREFETCH_MULTIPLIER = config('CELERY_WORKER_PREFETCH_MULTIPLIER', default=1, cast=int)
CELERY_TASK_ACKS_LATE = config('CELERY_TASK_ACKS_LATE', default=True, cast=bool)
CELERY_WORKER_MAX_TASKS_PER_CHILD = config('CELERY_WORKER_MAX_TASKS_PER_CHILD', default=1000, cast=int)

# Configuración de routing para tareas SRI
CELERY_TASK_ROUTES = {
    'apps.sri_integration.tasks.check_document_authorization_async': {'queue': 'sri_authorization'},
    'apps.sri_integration.tasks.process_document_async': {'queue': 'sri_processing'},
    'apps.sri_integration.tasks.cleanup_expired_documents': {'queue': 'sri_maintenance'},
}

# TTL para resultados
CELERY_RESULT_EXPIRES = config('CELERY_RESULT_EXPIRES', default=3600, cast=int)  # 1 hora

# Configuración de reintentos
CELERY_TASK_DEFAULT_MAX_RETRIES = config('CELERY_TASK_DEFAULT_MAX_RETRIES', default=3, cast=int)
CELERY_TASK_DEFAULT_RETRY_DELAY = config('CELERY_TASK_DEFAULT_RETRY_DELAY', default=60, cast=int)

# Configuración de monitoreo
CELERY_SEND_TASK_EVENTS = config('CELERY_SEND_TASK_EVENTS', default=True, cast=bool)
CELERY_TASK_SEND_SENT_EVENT = config('CELERY_TASK_SEND_SENT_EVENT', default=True, cast=bool)

# ==========================================
# GlobalCertificateManager CONFIGURATION
# ==========================================

CERTIFICATE_CACHE_TIMEOUT = config('CERTIFICATE_CACHE_TIMEOUT', default=3600, cast=int)  # 1 hora
MAX_CERTIFICATES_CACHE = config('MAX_CERTIFICATES_CACHE', default=1000, cast=int)
CERTIFICATE_CLEANUP_INTERVAL = config('CERTIFICATE_CLEANUP_INTERVAL', default=300, cast=int)  # 5 minutos

# Auto-precarga de certificados
CERTIFICATE_AUTO_PRELOAD = config('CERTIFICATE_AUTO_PRELOAD', default=True, cast=bool)
CERTIFICATE_AUTO_PRELOAD_DELAY = config('CERTIFICATE_AUTO_PRELOAD_DELAY', default=2, cast=int)
CERTIFICATE_AUTO_CLEANUP = config('CERTIFICATE_AUTO_CLEANUP', default=True, cast=bool)

# Configuración de validación de certificados
CERTIFICATE_VALIDATION_RULES = {
    'min_days_before_expiration_warning': config('CERT_EXPIRATION_WARNING_DAYS', default=30, cast=int),
    'max_certificate_file_size': config('CERT_MAX_FILE_SIZE', default=10 * 1024 * 1024, cast=int),  # 10 MB
    'allowed_certificate_formats': ['.p12', '.pfx'],
    'require_password': config('CERT_REQUIRE_PASSWORD', default=True, cast=bool),
}

# Configuración de seguridad para certificados
CERTIFICATE_ENCRYPTION_ALGORITHM = config('CERT_ENCRYPTION_ALGORITHM', default='AES-256-GCM')
CERTIFICATE_KEY_DERIVATION = config('CERT_KEY_DERIVATION', default='PBKDF2')

# Métricas y monitoreo
CERTIFICATE_METRICS_ENABLED = config('CERTIFICATE_METRICS_ENABLED', default=True, cast=bool)
CERTIFICATE_USAGE_LOGGING = config('CERTIFICATE_USAGE_LOGGING', default=True, cast=bool)

# Configuración de alertas por email
CERTIFICATE_ALERTS = {
    'email_on_expiration': config('CERTIFICATE_EMAIL_ALERTS', default=True, cast=bool),
    'email_on_load_failure': config('CERTIFICATE_EMAIL_ON_FAILURE', default=True, cast=bool),
    'days_before_expiration_alert': [
        config('CERT_ALERT_30_DAYS', default=30, cast=int),
        config('CERT_ALERT_7_DAYS', default=7, cast=int),
        config('CERT_ALERT_1_DAY', default=1, cast=int)
    ],
}

# Email para alertas de certificados
CERTIFICATE_ALERT_EMAIL = config('CERTIFICATE_ALERT_EMAIL', default=EMAIL_HOST_USER)

# ==========================================
# CACHE CONFIGURATION - ✅ CORREGIDO COMPLETAMENTE
# ==========================================

# ✅ CACHE CON DJANGO-REDIS (RECOMENDADO Y CORREGIDO)
CACHES = {
    'default': {
        'BACKEND': 'django_redis.cache.RedisCache',  # ✅ CORREGIDO: Usando django-redis
        'LOCATION': f'redis://{REDIS_AUTH}{REDIS_HOST}:{REDIS_PORT}/2',
        'TIMEOUT': config('CACHE_DEFAULT_TIMEOUT', default=300, cast=int),
        'OPTIONS': {
            'CLIENT_CLASS': 'django_redis.client.DefaultClient',
            'CONNECTION_POOL_KWARGS': {
                'max_connections': config('CACHE_MAX_CONNECTIONS', default=20, cast=int),
            }
        }
    },
    'certificates': {
        'BACKEND': 'django_redis.cache.RedisCache',  # ✅ CORREGIDO: Usando django-redis
        'LOCATION': f'redis://{REDIS_AUTH}{REDIS_HOST}:{REDIS_PORT}/3',
        'TIMEOUT': CERTIFICATE_CACHE_TIMEOUT,
        'OPTIONS': {
            'CLIENT_CLASS': 'django_redis.client.DefaultClient',
            'CONNECTION_POOL_KWARGS': {
                'max_connections': config('CACHE_CERT_MAX_CONNECTIONS', default=10, cast=int),
            }
        }
    },
    'sessions': {
        'BACKEND': 'django_redis.cache.RedisCache',  # ✅ CORREGIDO: Usando django-redis
        'LOCATION': f'redis://{REDIS_AUTH}{REDIS_HOST}:{REDIS_PORT}/4',
        'TIMEOUT': SESSION_COOKIE_AGE,
        'OPTIONS': {
            'CLIENT_CLASS': 'django_redis.client.DefaultClient',
        }
    }
}

# ==========================================
# CELERY BEAT SCHEDULE - ✅ AGREGADO
# ==========================================

from celery.schedules import crontab

CELERY_BEAT_SCHEDULE = {
    'check-pending-authorizations': {
        'task': 'apps.sri_integration.tasks.check_all_pending_authorizations',
        'schedule': 300.0,  # Cada 5 minutos
    },
    'cleanup-old-sri-responses': {
        'task': 'apps.sri_integration.tasks.cleanup_old_sri_responses',
        'schedule': crontab(hour=2, minute=0),  # Diario a las 2:00 AM
    },
    'retry-failed-documents': {
        'task': 'apps.sri_integration.tasks.retry_failed_documents',
        'schedule': 7200.0,  # Cada 2 horas
    },
    'generate-daily-report': {
        'task': 'apps.sri_integration.tasks.generate_daily_report',
        'schedule': crontab(hour=23, minute=30),  # Diario a las 11:30 PM
    },
}

# ==========================================
# SECURITY CONFIGURATION
# ==========================================

# Configuración de seguridad basada en .env
SECURE_SSL_REDIRECT = config('SECURE_SSL_REDIRECT', default=not DEBUG, cast=bool)
SECURE_HSTS_SECONDS = config('SECURE_HSTS_SECONDS', default=31536000, cast=int) if not DEBUG else 0
SECURE_HSTS_INCLUDE_SUBDOMAINS = config('SECURE_HSTS_INCLUDE_SUBDOMAINS', default=not DEBUG, cast=bool)
SECURE_HSTS_PRELOAD = config('SECURE_HSTS_PRELOAD', default=not DEBUG, cast=bool)
SECURE_CONTENT_TYPE_NOSNIFF = config('SECURE_CONTENT_TYPE_NOSNIFF', default=True, cast=bool)
SECURE_BROWSER_XSS_FILTER = config('SECURE_BROWSER_XSS_FILTER', default=True, cast=bool)
X_FRAME_OPTIONS = config('X_FRAME_OPTIONS', default='DENY')

# Configuración de archivos
FILE_UPLOAD_MAX_MEMORY_SIZE = config('FILE_UPLOAD_MAX_MEMORY_SIZE', default=5 * 1024 * 1024, cast=int)  # 5 MB
DATA_UPLOAD_MAX_MEMORY_SIZE = config('DATA_UPLOAD_MAX_MEMORY_SIZE', default=10 * 1024 * 1024, cast=int)  # 10 MB

# ==========================================
# LOGGING CONFIGURATION
# ==========================================

# Configuración de logging mejorada
LOG_LEVEL = config('LOG_LEVEL', default='INFO' if not DEBUG else 'DEBUG')
LOG_DIR = config('LOG_DIR', default='logs')

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
        'celery': {
            'format': '[CELERY] {asctime} {levelname}: {message}',
            'style': '{',
            'datefmt': '%Y-%m-%d %H:%M:%S'
        },
        'sri_integration': {
            'format': '[SRI] {asctime} {levelname}: {message}',
            'style': '{',
            'datefmt': '%Y-%m-%d %H:%M:%S'
        },
        'certificates': {
            'format': '[CERTIFICATES] {asctime} {levelname}: {message}',
            'style': '{',
            'datefmt': '%Y-%m-%d %H:%M:%S'
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
            'level': LOG_LEVEL,
        },
        'file': {
            'class': 'logging.FileHandler',
            'filename': os.path.join(BASE_DIR, 'logs', 'rutafact.log'),
            'formatter': 'verbose',
            'level': LOG_LEVEL,
        },
        'celery_file': {
            'class': 'logging.FileHandler',
            'filename': os.path.join(BASE_DIR, 'logs', 'celery.log'),
            'formatter': 'celery',
            'level': 'INFO',
        },
        'sri_file': {
            'class': 'logging.FileHandler',
            'filename': os.path.join(BASE_DIR, 'logs', 'sri_integration.log'),
            'formatter': 'sri_integration',
            'level': 'INFO',
        },
        'certificates_file': {
            'class': 'logging.FileHandler',
            'filename': os.path.join(BASE_DIR, 'logs', 'certificates.log'),
            'formatter': 'certificates',
            'level': 'INFO',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['console', 'file'],
            'level': LOG_LEVEL,
        },
        'celery': {
            'handlers': ['celery_file', 'console'],
            'level': 'INFO',
            'propagate': False,
        },
        'apps.sri_integration': {
            'handlers': ['sri_file', 'console'],
            'level': LOG_LEVEL,
            'propagate': False,
        },
        'apps.certificates': {
            'handlers': ['certificates_file', 'console'],
            'level': LOG_LEVEL,
            'propagate': False,
        },
        'apps.core': {
            'handlers': ['console', 'file'],
            'level': LOG_LEVEL,
            'propagate': False,
        },
        'apps.sri_integration.tasks': {
            'handlers': ['celery_file', 'sri_file', 'console'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}

# ==========================================
# SRI AUTO-SEND CONFIGURATION
# ==========================================

# Envío automático al SRI después de generar XML
SRI_AUTO_SEND = config('SRI_AUTO_SEND', default=True, cast=bool)
SRI_AUTO_SEND_AFTER_GENERATION = config('SRI_AUTO_SEND_AFTER_GENERATION', default=True, cast=bool)
SRI_AUTO_AUTHORIZE_CHECK = config('SRI_AUTO_AUTHORIZE_CHECK', default=True, cast=bool)
SRI_AUTO_EMAIL = config('SRI_AUTO_EMAIL', default=True, cast=bool)

# Configuración de reintentos automáticos
SRI_AUTO_RETRY_FAILED = config('SRI_AUTO_RETRY_FAILED', default=True, cast=bool)
SRI_MAX_RETRY_ATTEMPTS = config('SRI_MAX_RETRY_ATTEMPTS', default=3, cast=int)
SRI_RETRY_DELAY_SECONDS = config('SRI_RETRY_DELAY_SECONDS', default=60, cast=int)

# Configuración de procesamiento asíncrono
SRI_USE_ASYNC_PROCESSING = config('SRI_USE_ASYNC_PROCESSING', default=True, cast=bool)
SRI_ASYNC_TIMEOUT = config('SRI_ASYNC_TIMEOUT', default=300, cast=int)

# Configuración de estado de documentos SRI
SRI_AUTO_UPDATE_STATUS = config('SRI_AUTO_UPDATE_STATUS', default=True, cast=bool)
SRI_STATUS_CHECK_INTERVAL = config('SRI_STATUS_CHECK_INTERVAL', default=30, cast=int)
SRI_BATCH_SIZE = config('SRI_BATCH_SIZE', default=10, cast=int)

# Configuración de notificaciones automáticas
SRI_NOTIFY_ON_SUCCESS = config('SRI_NOTIFY_ON_SUCCESS', default=True, cast=bool)
SRI_NOTIFY_ON_ERROR = config('SRI_NOTIFY_ON_ERROR', default=True, cast=bool)
SRI_NOTIFY_ON_RETRY = config('SRI_NOTIFY_ON_RETRY', default=False, cast=bool)

# Configuración de limpieza automática
SRI_AUTO_CLEANUP_OLD_LOGS = config('SRI_AUTO_CLEANUP_OLD_LOGS', default=True, cast=bool)
SRI_CLEANUP_DAYS_THRESHOLD = config('SRI_CLEANUP_DAYS_THRESHOLD', default=90, cast=int)
SRI_CLEANUP_BATCH_SIZE = config('SRI_CLEANUP_BATCH_SIZE', default=100, cast=int)

# Configuración de cola y procesamiento en lote
SRI_QUEUE_PROCESSING = config('SRI_QUEUE_PROCESSING', default=True, cast=bool)
SRI_QUEUE_MAX_SIZE = config('SRI_QUEUE_MAX_SIZE', default=1000, cast=int)
SRI_QUEUE_BATCH_TIMEOUT = config('SRI_QUEUE_BATCH_TIMEOUT', default=300, cast=int)  # 5 minutos

# Configuración de validación previa al envío
SRI_PRE_VALIDATION = config('SRI_PRE_VALIDATION', default=True, cast=bool)
SRI_VALIDATE_XML_SCHEMA = config('SRI_VALIDATE_XML_SCHEMA', default=True, cast=bool)
SRI_VALIDATE_BUSINESS_RULES = config('SRI_VALIDATE_BUSINESS_RULES', default=True, cast=bool)

# Configuración de monitoreo y métricas
SRI_METRICS_ENABLED = config('SRI_METRICS_ENABLED', default=True, cast=bool)
SRI_PERFORMANCE_LOGGING = config('SRI_PERFORMANCE_LOGGING', default=True, cast=bool)
SRI_ERROR_TRACKING = config('SRI_ERROR_TRACKING', default=True, cast=bool)

# Configuración de archivos y almacenamiento
SRI_AUTO_BACKUP_DOCUMENTS = config('SRI_AUTO_BACKUP_DOCUMENTS', default=True, cast=bool)
SRI_BACKUP_RETENTION_DAYS = config('SRI_BACKUP_RETENTION_DAYS', default=365, cast=int)
SRI_COMPRESS_BACKUP_FILES = config('SRI_COMPRESS_BACKUP_FILES', default=True, cast=bool)

# Configuración de integración con webhook
SRI_WEBHOOK_ENABLED = config('SRI_WEBHOOK_ENABLED', default=False, cast=bool)
SRI_WEBHOOK_URL = config('SRI_WEBHOOK_URL', default='')
SRI_WEBHOOK_SECRET = config('SRI_WEBHOOK_SECRET', default='')
SRI_WEBHOOK_TIMEOUT = config('SRI_WEBHOOK_TIMEOUT', default=30, cast=int)

# Configuración de circuit breaker
SRI_CIRCUIT_BREAKER_ENABLED = config('SRI_CIRCUIT_BREAKER_ENABLED', default=True, cast=bool)
SRI_CIRCUIT_BREAKER_FAILURE_THRESHOLD = config('SRI_CIRCUIT_BREAKER_FAILURE_THRESHOLD', default=5, cast=int)
SRI_CIRCUIT_BREAKER_RECOVERY_TIMEOUT = config('SRI_CIRCUIT_BREAKER_RECOVERY_TIMEOUT', default=60, cast=int)

# ==========================================
# DEVELOPMENT SETTINGS
# ==========================================

if DEBUG:
    # Configuración específica para desarrollo
    CELERY_TASK_ALWAYS_EAGER = config('CELERY_TASK_ALWAYS_EAGER', default=False, cast=bool)
    CELERY_TASK_EAGER_PROPAGATES = config('CELERY_TASK_EAGER_PROPAGATES', default=True, cast=bool)
    
    # CORS más permisivo en desarrollo
    CORS_ALLOW_ALL_ORIGINS = config('CORS_ALLOW_ALL_ORIGINS', default=True, cast=bool)
    
    # Configuración de certificados más permisiva
    CERTIFICATE_CACHE_TIMEOUT = 1800  # 30 minutos
    MAX_CERTIFICATES_CACHE = 100
    CERTIFICATE_AUTO_PRELOAD_DELAY = 1
    
    # SRI más permisivo en desarrollo
    SRI_AUTO_RETRY_FAILED = False  # Evitar reintentos automáticos en desarrollo
    SRI_CIRCUIT_BREAKER_ENABLED = False  # Deshabilitar circuit breaker en desarrollo
    
    # Debug toolbar si está disponible
    try:
        import debug_toolbar
        INSTALLED_APPS += ['debug_toolbar']
        MIDDLEWARE += ['debug_toolbar.middleware.DebugToolbarMiddleware']
        INTERNAL_IPS = ['127.0.0.1', 'localhost']
    except ImportError:
        pass

# ==========================================
# PRODUCTION SETTINGS
# ==========================================

if not DEBUG:
    # Configuración optimizada para producción
    CERTIFICATE_CACHE_TIMEOUT = 7200  # 2 horas
    MAX_CERTIFICATES_CACHE = 5000
    CERTIFICATE_AUTO_PRELOAD_DELAY = 5
    
    # Configuración de Celery para producción
    CELERY_WORKER_PREFETCH_MULTIPLIER = 4
    CELERY_WORKER_MAX_TASKS_PER_CHILD = 1000
    
    # SRI optimizado para producción
    SRI_BATCH_SIZE = 20
    SRI_QUEUE_MAX_SIZE = 5000
    SRI_AUTO_BACKUP_DOCUMENTS = True
    SRI_COMPRESS_BACKUP_FILES = True
    
    # Logging menos verboso en producción
    LOGGING['loggers']['apps.sri_integration']['level'] = 'INFO'
    LOGGING['loggers']['apps.certificates']['level'] = 'INFO'

# ==========================================
# CREAR DIRECTORIOS NECESARIOS - ✅ OPTIMIZADO
# ==========================================

import os
import sys

# Solo crear directorios si no estamos en testing y solo una vez (proceso principal)
if 'test' not in sys.argv:
    directories_to_create = [
        'logs',
        'storage',
        'storage/logs',
        'storage/backups',
    ]

    for directory in directories_to_create:
        dir_path = BASE_DIR / directory
        try:
            os.makedirs(dir_path, exist_ok=True)
            # Permisos solo en carpetas críticas
            if 'certificates' in directory or 'backup' in directory:
                try:
                    os.chmod(dir_path, 0o700)
                except:
                    pass
        except Exception as e:
            if DEBUG:
                print(f"⚠️ No se pudo crear/acceder a {directory}: {e}")

# ==========================================
# ESTATUS DE CONFIGURACIÓN
# ==========================================

def print_config_status():
    """Imprimir resumen ligero del estado al iniciar"""
    if os.environ.get('RUN_MAIN') == 'true' or not DEBUG: # Evitar doble impresión en dev
        print(f"🚀 RutaFact_SRI | Modo: {'Desarrollo' if DEBUG else 'Producción'} | DB: {DATABASES['default']['NAME']}")
        if not EMAIL_HOST_USER:
             print("⚠️ Email no configurado")

# Ejecutar resumen solo si es el proceso principal
if 'manage.py' in sys.argv and 'runserver' in sys.argv:
    print_config_status()
elif 'daphne' in sys.argv or 'celery' in sys.argv:
    # Solo un log minimalista para servicios de fondo
    print(f"📦 Iniciando {sys.argv[0]}...")

# ==========================================
# VALIDACIÓN FINAL
# ==========================================

# Validar solo variables críticas extremas
if not SECRET_KEY or SECRET_KEY == 'django-insecure-rutafact-sri-change-this-in-production':
    if not DEBUG:
        raise ValueError("❌ SECRET_KEY crítica no configurada para producción")



# Redirects
LOGIN_REDIRECT_URL = '/dashboard/'
LOGOUT_REDIRECT_URL = '/accounts/login/'
