# Generated by Django 5.2.3 on 2025-07-12 01:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCompanyAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('waiting', 'En Sala de Espera'), ('assigned', 'Asignado'), ('rejected', 'Rechazado'), ('suspended', 'Suspendido')], default='waiting', max_length=20, verbose_name='Estado')),
                ('assigned_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Asignación')),
                ('notes', models.TextField(blank=True, verbose_name='Notas del Administrador')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users_assigned', to=settings.AUTH_USER_MODEL, verbose_name='Asignado por')),
                ('assigned_companies', models.ManyToManyField(blank=True, related_name='assigned_users', to='companies.company', verbose_name='Empresas Asignadas')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='company_assignment', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Asignación de Usuario',
                'verbose_name_plural': 'Asignaciones de Usuarios',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AdminNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('user_waiting', 'Usuario en Sala de Espera'), ('user_registered', 'Nuevo Usuario Registrado'), ('company_request', 'Solicitud de Empresa'), ('system_alert', 'Alerta del Sistema')], max_length=20, verbose_name='Tipo de Notificación')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('message', models.TextField(verbose_name='Mensaje')),
                ('priority', models.CharField(choices=[('low', 'Baja'), ('normal', 'Normal'), ('high', 'Alta'), ('urgent', 'Urgente')], default='normal', max_length=10, verbose_name='Prioridad')),
                ('is_read', models.BooleanField(default=False, verbose_name='Leída')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Lectura')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('read_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='read_notifications', to=settings.AUTH_USER_MODEL, verbose_name='Leída por')),
                ('related_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admin_notifications', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Relacionado')),
            ],
            options={
                'verbose_name': 'Notificación de Admin',
                'verbose_name_plural': 'Notificaciones de Admin',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['is_read', '-created_at'], name='users_admin_is_read_0e73d4_idx'), models.Index(fields=['notification_type'], name='users_admin_notific_dcbc07_idx'), models.Index(fields=['priority'], name='users_admin_priorit_19d2c6_idx')],
            },
        ),
    ]
