# Generated by Django 5.2.3 on 2025-07-23 22:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_add_waiting_room_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de aprobación'),
        ),
        migrations.AddField(
            model_name='user',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_users', to=settings.AUTH_USER_MODEL, verbose_name='Aprobado por'),
        ),
        migrations.AddField(
            model_name='user',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True, verbose_name='Razón de rechazo'),
        ),
        migrations.AddField(
            model_name='user',
            name='suspension_reason',
            field=models.TextField(blank=True, null=True, verbose_name='Razón de suspensión'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_status',
            field=models.CharField(choices=[('waiting', 'En Sala de Espera'), ('active', 'Activo'), ('suspended', 'Suspendido'), ('rejected', 'Rechazado')], default='waiting', max_length=20, verbose_name='Estado del Usuario'),
        ),
    ]
