# Generated by Django 5.2.12 on 2026-03-29 05:34

import apps.users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_add_user_status_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, help_text='Optional profile picture.', null=True, upload_to=apps.users.models.user_profile_pic_upload_path, verbose_name='profile picture'),
        ),
    ]
