# Generated by Django 5.2.13 on 2026-04-17 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrador'), ('dispatcher', 'Despachador'), ('client', 'Cliente')], default='client', max_length=20, verbose_name='Rol del Usuario'),
        ),
        migrations.AlterField(
            model_name='usercompanyassignment',
            name='status',
            field=models.CharField(choices=[('waiting', 'En Sala de Espera'), ('assigned', 'Asignado'), ('rejected', 'Rechazado'), ('suspended', 'Suspendido')], default='assigned', max_length=20, verbose_name='Estado'),
        ),
    ]
