# Generated by Django 5.2.13 on 2026-04-23 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_role_alter_usercompanyassignment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='can_track',
            field=models.BooleanField(default=False, help_text='Indica si el usuario tiene permiso para iniciar rastreo GPS en el móvil.', verbose_name='Puede Rastrear Ruta'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrador'), ('seller', 'Vendedor'), ('dispatcher', 'Despachador'), ('driver', 'Transportador'), ('client', 'Cliente')], default='client', max_length=20, verbose_name='Rol del Usuario'),
        ),
    ]
