# Generated by Django 5.2.3 on 2025-07-11 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when the record was created.', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the record was last updated.', verbose_name='updated at')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this record should be treated as active.', verbose_name='is active')),
                ('action', models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('EXPORT', 'Export'), ('IMPORT', 'Import'), ('SEND', 'Send'), ('RECEIVE', 'Receive'), ('AUTHORIZE', 'Authorize'), ('REJECT', 'Reject')], help_text='Type of action performed.', max_length=20, verbose_name='action')),
                ('model_name', models.CharField(help_text='Name of the model affected.', max_length=100, verbose_name='model name')),
                ('object_id', models.CharField(blank=True, help_text='ID of the object affected.', max_length=100, verbose_name='object ID')),
                ('object_representation', models.CharField(blank=True, help_text='String representation of the object.', max_length=255, verbose_name='object representation')),
                ('changes', models.JSONField(blank=True, default=dict, help_text='JSON representation of changes made.', verbose_name='changes')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address from which the action was performed.', null=True, verbose_name='IP address')),
                ('user_agent', models.TextField(blank=True, help_text='Browser/client information.', verbose_name='user agent')),
                ('additional_data', models.JSONField(blank=True, default=dict, help_text='Additional context data.', verbose_name='additional data')),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FileUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when the record was created.', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the record was last updated.', verbose_name='updated at')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this record should be treated as active.', verbose_name='is active')),
                ('file', models.FileField(help_text='Uploaded file.', upload_to='uploads/%Y/%m/%d/', verbose_name='file')),
                ('original_name', models.CharField(help_text='Original name of the uploaded file.', max_length=255, verbose_name='original file name')),
                ('file_type', models.CharField(choices=[('DOCUMENT', 'Document'), ('IMAGE', 'Image'), ('CERTIFICATE', 'Certificate'), ('BACKUP', 'Backup'), ('EXPORT', 'Export'), ('IMPORT', 'Import'), ('LOG', 'Log')], default='DOCUMENT', help_text='Type of file uploaded.', max_length=20, verbose_name='file type')),
                ('file_size', models.PositiveIntegerField(help_text='Size of the file in bytes.', verbose_name='file size')),
                ('mime_type', models.CharField(blank=True, help_text='MIME type of the file.', max_length=100, verbose_name='MIME type')),
                ('description', models.TextField(blank=True, help_text='Description of the file.', verbose_name='description')),
                ('is_public', models.BooleanField(default=False, help_text='Whether this file can be accessed publicly.', verbose_name='is public')),
                ('checksum', models.CharField(blank=True, help_text='File checksum for integrity verification.', max_length=64, verbose_name='checksum')),
            ],
            options={
                'verbose_name': 'File Upload',
                'verbose_name_plural': 'File Uploads',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SystemConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when the record was created.', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the record was last updated.', verbose_name='updated at')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this record should be treated as active.', verbose_name='is active')),
                ('key', models.CharField(help_text='Unique identifier for the configuration.', max_length=100, unique=True, verbose_name='configuration key')),
                ('value', models.TextField(help_text='Configuration value (can be JSON).', verbose_name='configuration value')),
                ('config_type', models.CharField(choices=[('SYSTEM', 'System'), ('SRI', 'SRI'), ('EMAIL', 'Email'), ('NOTIFICATION', 'Notification'), ('SECURITY', 'Security'), ('BACKUP', 'Backup')], default='SYSTEM', help_text='Type of configuration.', max_length=20, verbose_name='configuration type')),
                ('description', models.TextField(blank=True, help_text='Description of what this configuration does.', verbose_name='description')),
                ('is_sensitive', models.BooleanField(default=False, help_text='Whether this configuration contains sensitive data.', verbose_name='is sensitive')),
            ],
            options={
                'verbose_name': 'System Configuration',
                'verbose_name_plural': 'System Configurations',
                'ordering': ['config_type', 'key'],
            },
        ),
    ]
