# Generated by Django 5.2.3 on 2025-07-18 06:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('VIEW', 'View'), ('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('LOGIN_FAILED', 'Login Failed'), ('EXPORT', 'Export'), ('IMPORT', 'Import'), ('UPLOAD', 'Upload'), ('DOWNLOAD', 'Download'), ('SEND', 'Send'), ('RECEIVE', 'Receive'), ('AUTHORIZE', 'Authorize'), ('REJECT', 'Reject'), ('APPROVE', 'Approve'), ('DENY', 'Deny'), ('SRI_RESPONSE', 'SRI Response'), ('SRI_SENT', 'SRI Sent'), ('SRI_RECEIVED', 'SRI Received'), ('SRI_AUTHORIZED', 'SRI Authorized'), ('SRI_REJECTED', 'SRI Rejected'), ('SRI_ERROR', 'SRI Error'), ('SRI_TIMEOUT', 'SRI Timeout'), ('SRI_VALIDATION', 'SRI Validation'), ('DOCUMENT_GENERATED', 'Document Generated'), ('DOCUMENT_SIGNED', 'Document Signed'), ('DOCUMENT_VALIDATED', 'Document Validated'), ('DOCUMENT_CANCELLED', 'Document Cancelled'), ('XML_GENERATED', 'XML Generated'), ('XML_SIGNED', 'XML Signed'), ('XML_VALIDATED', 'XML Validated'), ('XML_ERROR', 'XML Error'), ('CERTIFICATE_LOADED', 'Certificate Loaded'), ('CERTIFICATE_EXPIRED', 'Certificate Expired'), ('CERTIFICATE_ERROR', 'Certificate Error'), ('SYSTEM_START', 'System Start'), ('SYSTEM_STOP', 'System Stop'), ('BACKUP_CREATED', 'Backup Created'), ('BACKUP_RESTORED', 'Backup Restored'), ('CONFIG_CHANGED', 'Configuration Changed'), ('SETTINGS_UPDATED', 'Settings Updated'), ('ERROR_OCCURRED', 'Error Occurred'), ('WARNING_ISSUED', 'Warning Issued'), ('EXCEPTION_CAUGHT', 'Exception Caught')], help_text='Type of action performed.', max_length=50, verbose_name='action'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['action', 'model_name'], name='core_auditl_action_a7fec1_idx'),
        ),
    ]
