# Generated by Django 5.2.13 on 2026-04-09 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_add_comprehensive_audit_actions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(help_text='Type of action performed.', max_length=50, verbose_name='action'),
        ),
    ]
