# Generated by Django 6.0.3 on 2026-05-03 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_route'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='contact phone'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_reference',
            field=models.TextField(blank=True, help_text='Barrio, color de casa, etc.', verbose_name='delivery reference'),
        ),
    ]
