# Generated by Django 5.2.13 on 2026-05-03 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=9, max_digits=12, null=True, verbose_name='latitude'),
        ),
        migrations.AddField(
            model_name='order',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=9, max_digits=12, null=True, verbose_name='longitude'),
        ),
    ]
