# Generated by Django 5.2.13 on 2026-05-03 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_latitude_order_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='document_type',
            field=models.CharField(choices=[('factura', 'Factura SRI'), ('nota_entrega', 'Nota de Entrega Interna')], default='factura', max_length=20, verbose_name='document type'),
        ),
    ]
