# Generated by Django 5.2.3 on 2025-07-23 19:01

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0002_companyapitoken'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre del Plan')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('invoice_limit', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Límite de Facturas')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Precio (USD)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Plan Destacado')),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='Para ordenar los planes en la interfaz', verbose_name='Orden')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
            ],
            options={
                'verbose_name': 'Plan de Facturación',
                'verbose_name_plural': 'Planes de Facturación',
                'ordering': ['sort_order', 'price'],
            },
        ),
        migrations.CreateModel(
            name='CompanyBillingProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available_invoices', models.PositiveIntegerField(default=0, verbose_name='Facturas Disponibles')),
                ('total_invoices_purchased', models.PositiveIntegerField(default=0, verbose_name='Total Facturas Compradas')),
                ('total_invoices_consumed', models.PositiveIntegerField(default=0, verbose_name='Total Facturas Consumidas')),
                ('total_spent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Total Gastado (USD)')),
                ('last_purchase_date', models.DateTimeField(blank=True, null=True, verbose_name='Última Compra')),
                ('auto_renewal_enabled', models.BooleanField(default=False, help_text='Para futuras funcionalidades', verbose_name='Renovación Automática')),
                ('low_balance_threshold', models.PositiveIntegerField(default=5, help_text='Notificar cuando queden X facturas', verbose_name='Umbral de Alerta')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='billing_profile', to='companies.company')),
            ],
            options={
                'verbose_name': 'Perfil de Facturación',
                'verbose_name_plural': 'Perfiles de Facturación',
            },
        ),
        migrations.CreateModel(
            name='InvoiceConsumption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_id', models.CharField(help_text='ID de la factura emitida', max_length=100, verbose_name='ID de Factura')),
                ('invoice_type', models.CharField(default='invoice', max_length=50, verbose_name='Tipo de Documento')),
                ('consumed_at', models.DateTimeField(auto_now_add=True, verbose_name='Consumido el')),
                ('balance_before', models.PositiveIntegerField(verbose_name='Saldo Anterior')),
                ('balance_after', models.PositiveIntegerField(verbose_name='Saldo Posterior')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Dirección IP')),
                ('api_endpoint', models.CharField(blank=True, max_length=200, verbose_name='Endpoint API')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_consumptions', to='companies.company')),
            ],
            options={
                'verbose_name': 'Consumo de Factura',
                'verbose_name_plural': 'Consumos de Facturas',
                'ordering': ['-consumed_at'],
            },
        ),
        migrations.CreateModel(
            name='PlanPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='ID de Compra')),
                ('plan_name', models.CharField(max_length=100, verbose_name='Nombre del Plan')),
                ('plan_invoice_limit', models.PositiveIntegerField(verbose_name='Facturas del Plan')),
                ('plan_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio del Plan')),
                ('payment_status', models.CharField(choices=[('pending', 'Pendiente de Validación'), ('approved', 'Aprobado'), ('rejected', 'Rechazado'), ('expired', 'Expirado')], default='pending', max_length=20, verbose_name='Estado')),
                ('payment_method', models.CharField(choices=[('bank_transfer', 'Transferencia Bancaria'), ('deposit', 'Depósito Bancario'), ('other', 'Otro')], default='bank_transfer', max_length=20, verbose_name='Método de Pago')),
                ('payer_name', models.CharField(max_length=200, verbose_name='Nombre del Pagador')),
                ('payer_document', models.CharField(help_text='Cédula, RUC, etc.', max_length=50, verbose_name='Documento del Pagador')),
                ('payment_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto Pagado')),
                ('payment_reference', models.CharField(blank=True, max_length=100, verbose_name='Referencia/Número de Transacción')),
                ('payment_date', models.DateField(verbose_name='Fecha de Pago')),
                ('bank_name', models.CharField(blank=True, max_length=100, verbose_name='Banco')),
                ('payment_receipt', models.FileField(help_text='JPG, PNG o PDF', upload_to='billing/receipts/%Y/%m/', verbose_name='Comprobante de Pago')),
                ('customer_notes', models.TextField(blank=True, help_text='Observaciones adicionales del cliente', verbose_name='Notas del Cliente')),
                ('admin_notes', models.TextField(blank=True, help_text='Observaciones internas', verbose_name='Notas del Administrador')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='Procesado el')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_purchases', to='companies.company')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='billing.plan')),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_purchases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Compra de Plan',
                'verbose_name_plural': 'Compras de Planes',
                'ordering': ['-created_at'],
            },
        ),
    ]
