# Generated by Django 5.2.3 on 2025-07-24 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_fix_plan_purchase_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planpurchase',
            name='plan_invoice_limit',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Facturas del Plan'),
        ),
        migrations.AlterField(
            model_name='planpurchase',
            name='plan_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nombre del Plan'),
        ),
        migrations.AlterField(
            model_name='planpurchase',
            name='plan_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Precio del Plan'),
        ),
    ]
