# Generated by Django 5.2.12 on 2026-03-29 05:34

import apps.billing.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_alter_planpurchase_plan_invoice_limit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planpurchase',
            name='payment_receipt',
            field=models.FileField(help_text='JPG, PNG o PDF', upload_to=apps.billing.models.billing_receipt_upload_path, verbose_name='Comprobante de Pago'),
        ),
    ]
