# Generated by Django 5.2.13 on 2026-04-09 22:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_alter_planpurchase_payment_receipt'),
    ]

    operations = [
        migrations.AddField(
            model_name='companybillingprofile',
            name='is_unlimited',
            field=models.BooleanField(default=False, verbose_name='Plan Ilimitado'),
        ),
        migrations.AddField(
            model_name='plan',
            name='is_unlimited',
            field=models.BooleanField(default=False, help_text='Si se marca, el límite de facturas se ignora', verbose_name='Facturas Ilimitadas'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='invoice_limit',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Límite de Facturas'),
        ),
    ]
