# Generated by Django 5.2.3 on 2025-07-11 18:52

import apps.certificates.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DigitalCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when the record was created.', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the record was last updated.', verbose_name='updated at')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this record should be treated as active.', verbose_name='is active')),
                ('certificate_file', models.FileField(help_text='P12 certificate file', upload_to=apps.certificates.models.certificate_upload_path, verbose_name='certificate file')),
                ('password_hash', models.CharField(help_text='Hashed password for the certificate', max_length=128, verbose_name='password hash')),
                ('subject_name', models.CharField(help_text='Certificate subject name', max_length=255, verbose_name='subject name')),
                ('issuer_name', models.CharField(help_text='Certificate issuer name', max_length=255, verbose_name='issuer name')),
                ('serial_number', models.CharField(help_text='Certificate serial number', max_length=100, verbose_name='serial number')),
                ('valid_from', models.DateTimeField(help_text='Certificate validity start date', verbose_name='valid from')),
                ('valid_to', models.DateTimeField(help_text='Certificate expiration date', verbose_name='valid to')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('EXPIRED', 'Expired'), ('REVOKED', 'Revoked'), ('INACTIVE', 'Inactive')], default='ACTIVE', help_text='Certificate status', max_length=20, verbose_name='status')),
                ('fingerprint', models.CharField(help_text='Certificate fingerprint (SHA256)', max_length=64, unique=True, verbose_name='fingerprint')),
                ('environment', models.CharField(choices=[('PRODUCTION', 'Production'), ('TEST', 'Test')], default='TEST', help_text='SRI environment for this certificate', max_length=20, verbose_name='environment')),
                ('company', models.OneToOneField(help_text='Company that owns this certificate', on_delete=django.db.models.deletion.CASCADE, related_name='digital_certificate', to='companies.company', verbose_name='company')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='updated by')),
            ],
            options={
                'verbose_name': 'Digital Certificate',
                'verbose_name_plural': 'Digital Certificates',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CertificateUsageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when the record was created.', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the record was last updated.', verbose_name='updated at')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this record should be treated as active.', verbose_name='is active')),
                ('operation', models.CharField(help_text='Type of operation performed', max_length=50, verbose_name='operation')),
                ('document_type', models.CharField(blank=True, help_text='Type of document signed', max_length=20, verbose_name='document type')),
                ('document_number', models.CharField(blank=True, help_text='Document number or identifier', max_length=50, verbose_name='document number')),
                ('success', models.BooleanField(default=True, help_text='Whether the operation was successful', verbose_name='success')),
                ('error_message', models.TextField(blank=True, help_text='Error message if operation failed', verbose_name='error message')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP address')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='updated by')),
                ('certificate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_logs', to='certificates.digitalcertificate', verbose_name='certificate')),
            ],
            options={
                'verbose_name': 'Certificate Usage Log',
                'verbose_name_plural': 'Certificate Usage Logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
