# Generated by Django 5.2.11 on 2026-02-05 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0002_add_storage_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='digitalcertificate',
            name='encrypted_password',
            field=models.TextField(blank=True, help_text='Certificate password encrypted with Fernet (AES-128)', null=True, verbose_name='encrypted password'),
        ),
        migrations.AlterField(
            model_name='digitalcertificate',
            name='password_hash',
            field=models.CharField(help_text='Hashed password for the certificate (LEGACY)', max_length=128, verbose_name='password hash'),
        ),
    ]
