# Generated by Django 5.2.13 on 2026-04-09 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0003_digitalcertificate_encrypted_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='digitalcertificate',
            name='storage_path',
            field=models.CharField(blank=True, help_text='DEPRECATED: Path to certificate file in storage/certificates/ directory. Use certificate_file instead.', max_length=500, null=True, verbose_name='storage path'),
        ),
    ]
