# Generated by Django 5.2.13 on 2026-04-21 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0004_alter_digitalcertificate_storage_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='digitalcertificate',
            name='extracted_name',
            field=models.CharField(blank=True, help_text='Name or Business Name extracted from certificate', max_length=255, null=True, verbose_name='extracted name'),
        ),
        migrations.AddField(
            model_name='digitalcertificate',
            name='extracted_ruc',
            field=models.CharField(blank=True, help_text='RUC extracted from certificate', max_length=13, null=True, verbose_name='extracted RUC'),
        ),
    ]
