# Generated by Django 5.2.3 on 2025-07-11 18:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when the record was created.', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the record was last updated.', verbose_name='updated at')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this record should be treated as active.', verbose_name='is active')),
                ('main_code', models.CharField(help_text='Product main code', max_length=25, verbose_name='main code')),
                ('auxiliary_code', models.CharField(blank=True, help_text='Product auxiliary code', max_length=25, verbose_name='auxiliary code')),
                ('description', models.TextField(help_text='Product description', verbose_name='description')),
                ('quantity', models.DecimalField(decimal_places=6, max_digits=12, verbose_name='quantity')),
                ('unit_price', models.DecimalField(decimal_places=6, max_digits=12, verbose_name='unit price')),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='discount')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='subtotal')),
                ('additional_details', models.JSONField(blank=True, default=dict, verbose_name='additional details')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='updated by')),
            ],
            options={
                'verbose_name': 'Document Item',
                'verbose_name_plural': 'Document Items',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ElectronicDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when the record was created.', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the record was last updated.', verbose_name='updated at')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this record should be treated as active.', verbose_name='is active')),
                ('document_type', models.CharField(choices=[('INVOICE', 'Invoice'), ('CREDIT_NOTE', 'Credit Note'), ('DEBIT_NOTE', 'Debit Note'), ('RETENTION', 'Retention'), ('REMISSION_GUIDE', 'Remission Guide')], max_length=20, verbose_name='document type')),
                ('document_number', models.CharField(help_text='Format: 001-001-000000001', max_length=17, verbose_name='document number')),
                ('access_key', models.CharField(help_text='49-digit access key', max_length=49, unique=True, verbose_name='access key')),
                ('issue_date', models.DateField(verbose_name='issue date')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('GENERATED', 'Generated'), ('SIGNED', 'Signed'), ('SENT', 'Sent to SRI'), ('AUTHORIZED', 'Authorized'), ('REJECTED', 'Rejected'), ('ERROR', 'Error')], default='DRAFT', max_length=20, verbose_name='status')),
                ('customer_identification_type', models.CharField(choices=[('04', 'RUC'), ('05', 'Cedula'), ('06', 'Passport'), ('07', 'Consumer'), ('08', 'Foreign ID')], max_length=2, verbose_name='customer identification type')),
                ('customer_identification', models.CharField(max_length=20, verbose_name='customer identification')),
                ('customer_name', models.CharField(max_length=300, verbose_name='customer name')),
                ('customer_address', models.TextField(blank=True, verbose_name='customer address')),
                ('customer_email', models.EmailField(blank=True, max_length=254, verbose_name='customer email')),
                ('customer_phone', models.CharField(blank=True, max_length=20, verbose_name='customer phone')),
                ('subtotal_without_tax', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='subtotal without tax')),
                ('subtotal_with_tax', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='subtotal with tax')),
                ('total_discount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='total discount')),
                ('total_tax', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='total tax')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='total amount')),
                ('xml_file', models.FileField(blank=True, upload_to='invoices/xml/', verbose_name='XML file')),
                ('signed_xml_file', models.FileField(blank=True, upload_to='invoices/xml/', verbose_name='signed XML file')),
                ('pdf_file', models.FileField(blank=True, upload_to='invoices/pdf/', verbose_name='PDF file')),
                ('sri_authorization_code', models.CharField(blank=True, max_length=49, verbose_name='SRI authorization code')),
                ('sri_authorization_date', models.DateTimeField(blank=True, null=True, verbose_name='SRI authorization date')),
                ('sri_response', models.JSONField(blank=True, default=dict, verbose_name='SRI response')),
                ('email_sent', models.BooleanField(default=False, verbose_name='email sent')),
                ('email_sent_date', models.DateTimeField(blank=True, null=True, verbose_name='email sent date')),
                ('additional_data', models.JSONField(blank=True, default=dict, verbose_name='additional data')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='electronic_documents', to='companies.company', verbose_name='company')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='updated by')),
            ],
            options={
                'verbose_name': 'Electronic Document',
                'verbose_name_plural': 'Electronic Documents',
            },
        ),
        migrations.CreateModel(
            name='DocumentTax',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when the record was created.', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the record was last updated.', verbose_name='updated at')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this record should be treated as active.', verbose_name='is active')),
                ('tax_code', models.CharField(choices=[('2', 'IVA'), ('3', 'ICE'), ('5', 'IRBPNR')], max_length=2, verbose_name='tax code')),
                ('percentage_code', models.CharField(choices=[('0', '0%'), ('2', '12%'), ('3', '14%'), ('6', 'No Objeto de Impuesto'), ('7', 'Exento de IVA')], max_length=2, verbose_name='percentage code')),
                ('rate', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='tax rate')),
                ('taxable_base', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='taxable base')),
                ('tax_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='tax amount')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='taxes', to='sri_integration.documentitem', verbose_name='item')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='updated by')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taxes', to='sri_integration.electronicdocument', verbose_name='document')),
            ],
            options={
                'verbose_name': 'Document Tax',
                'verbose_name_plural': 'Document Taxes',
            },
        ),
        migrations.AddField(
            model_name='documentitem',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sri_integration.electronicdocument', verbose_name='document'),
        ),
        migrations.CreateModel(
            name='SRIConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when the record was created.', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the record was last updated.', verbose_name='updated at')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this record should be treated as active.', verbose_name='is active')),
                ('environment', models.CharField(choices=[('PRODUCTION', 'Production'), ('TEST', 'Test')], default='TEST', help_text='SRI environment', max_length=20, verbose_name='environment')),
                ('reception_url', models.URLField(help_text='SRI reception service URL', verbose_name='reception URL')),
                ('authorization_url', models.URLField(help_text='SRI authorization service URL', verbose_name='authorization URL')),
                ('establishment_code', models.CharField(default='001', help_text='Establishment code (3 digits)', max_length=3, verbose_name='establishment code')),
                ('emission_point', models.CharField(default='001', help_text='Emission point code (3 digits)', max_length=3, verbose_name='emission point')),
                ('invoice_sequence', models.PositiveIntegerField(default=1, help_text='Current invoice sequence number', verbose_name='invoice sequence')),
                ('credit_note_sequence', models.PositiveIntegerField(default=1, help_text='Current credit note sequence number', verbose_name='credit note sequence')),
                ('debit_note_sequence', models.PositiveIntegerField(default=1, help_text='Current debit note sequence number', verbose_name='debit note sequence')),
                ('retention_sequence', models.PositiveIntegerField(default=1, help_text='Current retention sequence number', verbose_name='retention sequence')),
                ('remission_guide_sequence', models.PositiveIntegerField(default=1, help_text='Current remission guide sequence number', verbose_name='remission guide sequence')),
                ('email_enabled', models.BooleanField(default=True, help_text='Enable automatic email sending', verbose_name='email enabled')),
                ('email_subject_template', models.CharField(default='Documento Electrónico - {document_type} {document_number}', help_text='Email subject template', max_length=255, verbose_name='email subject template')),
                ('email_body_template', models.TextField(default='Estimado cliente,\n\nEn archivo adjunto encontrará su {document_type} electrónico número {document_number}.\n\nSaludos cordiales.', help_text='Email body template', verbose_name='email body template')),
                ('special_taxpayer', models.BooleanField(default=False, help_text='Is special taxpayer', verbose_name='special taxpayer')),
                ('special_taxpayer_number', models.CharField(blank=True, help_text='Special taxpayer resolution number', max_length=20, verbose_name='special taxpayer number')),
                ('accounting_required', models.BooleanField(default=True, help_text='Required to keep accounting', verbose_name='accounting required')),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sri_configuration', to='companies.company', verbose_name='company')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='updated by')),
            ],
            options={
                'verbose_name': 'SRI Configuration',
                'verbose_name_plural': 'SRI Configurations',
            },
        ),
        migrations.CreateModel(
            name='SRIResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when the record was created.', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the record was last updated.', verbose_name='updated at')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this record should be treated as active.', verbose_name='is active')),
                ('operation_type', models.CharField(choices=[('RECEPTION', 'Reception'), ('AUTHORIZATION', 'Authorization')], max_length=20, verbose_name='operation type')),
                ('response_code', models.CharField(max_length=10, verbose_name='response code')),
                ('response_message', models.TextField(verbose_name='response message')),
                ('raw_response', models.JSONField(default=dict, verbose_name='raw response')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sri_responses', to='sri_integration.electronicdocument', verbose_name='document')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='updated by')),
            ],
            options={
                'verbose_name': 'SRI Response',
                'verbose_name_plural': 'SRI Responses',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='electronicdocument',
            index=models.Index(fields=['company', 'status'], name='sri_integra_company_134b78_idx'),
        ),
        migrations.AddIndex(
            model_name='electronicdocument',
            index=models.Index(fields=['access_key'], name='sri_integra_access__af2cd7_idx'),
        ),
        migrations.AddIndex(
            model_name='electronicdocument',
            index=models.Index(fields=['issue_date'], name='sri_integra_issue_d_ebe8d8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='electronicdocument',
            unique_together={('company', 'document_number', 'document_type')},
        ),
    ]
