# Generated by Django 5.2.3 on 2025-07-14 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sri_integration', '0002_sriconfiguration_purchase_settlement_sequence_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sriconfiguration',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Configuration is active', verbose_name='is active'),
        ),
    ]
