# Generated by Django 5.2.3 on 2025-07-18 17:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sri_integration', '0003_alter_sriconfiguration_is_active'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentitem',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Maximum: 9,999,999,999.99', max_digits=12, verbose_name='discount'),
        ),
        migrations.AlterField(
            model_name='documentitem',
            name='quantity',
            field=models.DecimalField(decimal_places=6, help_text='Maximum: 999,999.999999', max_digits=12, verbose_name='quantity'),
        ),
        migrations.AlterField(
            model_name='documentitem',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, help_text='Calculated automatically. Maximum: 9,999,999,999.99', max_digits=12, verbose_name='subtotal'),
        ),
        migrations.AlterField(
            model_name='documentitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=6, help_text='Maximum: 999,999.999999', max_digits=12, verbose_name='unit price'),
        ),
        migrations.AlterField(
            model_name='purchasesettlementitem',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Maximum: 9,999,999,999.99', max_digits=12, verbose_name='discount'),
        ),
        migrations.AlterField(
            model_name='purchasesettlementitem',
            name='quantity',
            field=models.DecimalField(decimal_places=6, help_text='Maximum: 999,999.999999', max_digits=12, verbose_name='quantity'),
        ),
        migrations.AlterField(
            model_name='purchasesettlementitem',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, help_text='Calculated automatically. Maximum: 9,999,999,999.99', max_digits=12, verbose_name='subtotal'),
        ),
        migrations.AlterField(
            model_name='purchasesettlementitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=6, help_text='Maximum: 999,999.999999', max_digits=12, verbose_name='unit price'),
        ),
        migrations.AddIndex(
            model_name='documentitem',
            index=models.Index(fields=['document', 'main_code'], name='sri_integra_documen_a82778_idx'),
        ),
        migrations.AddIndex(
            model_name='purchasesettlementitem',
            index=models.Index(fields=['settlement', 'main_code'], name='sri_integra_settlem_0d2b5a_idx'),
        ),
    ]
