# Generated by Django 5.2.3 on 2025-07-31 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sri_integration', '0004_alter_documentitem_discount_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchasesettlement',
            options={'verbose_name': 'Purchase Settlement', 'verbose_name_plural': 'Purchase Settings'},
        ),
        migrations.RemoveField(
            model_name='sriconfiguration',
            name='authorization_url',
        ),
        migrations.RemoveField(
            model_name='sriconfiguration',
            name='reception_url',
        ),
        migrations.AlterField(
            model_name='documenttax',
            name='percentage_code',
            field=models.CharField(choices=[('0', '0%'), ('2', '12%'), ('3', '14%'), ('4', '15%'), ('6', 'No Objeto de Impuesto'), ('7', 'Exento de IVA')], max_length=2, verbose_name='percentage code'),
        ),
    ]
