# Generated by Django 5.2.6 on 2025-09-16 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sri_integration', '0005_alter_purchasesettlement_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sriconfiguration',
            name='auto_backup_documents',
            field=models.BooleanField(default=True, help_text='Automatically backup processed documents', verbose_name='auto backup documents'),
        ),
        migrations.AddField(
            model_name='sriconfiguration',
            name='auto_cleanup_old_logs',
            field=models.BooleanField(default=True, help_text='Automatically cleanup old processing logs', verbose_name='auto cleanup old logs'),
        ),
        migrations.AddField(
            model_name='sriconfiguration',
            name='auto_retry',
            field=models.BooleanField(default=True, help_text='Retry automatically if sending fails', verbose_name='auto retry'),
        ),
        migrations.AddField(
            model_name='sriconfiguration',
            name='auto_send',
            field=models.BooleanField(default=True, help_text='Send automatically to SRI after generation', verbose_name='auto send'),
        ),
        migrations.AddField(
            model_name='sriconfiguration',
            name='auto_send_after_generation',
            field=models.BooleanField(default=True, help_text='Automatically send to SRI immediately after XML generation', verbose_name='auto send after generation'),
        ),
        migrations.AddField(
            model_name='sriconfiguration',
            name='backup_retention_days',
            field=models.IntegerField(default=365, help_text='Days to retain document backups', verbose_name='backup retention days'),
        ),
        migrations.AddField(
            model_name='sriconfiguration',
            name='batch_size',
            field=models.IntegerField(default=10, help_text='Number of documents to process in each batch', verbose_name='batch size'),
        ),
        migrations.AddField(
            model_name='sriconfiguration',
            name='circuit_breaker_enabled',
            field=models.BooleanField(default=True, help_text='Enable circuit breaker to prevent repeated failures', verbose_name='circuit breaker enabled'),
        ),
        migrations.AddField(
            model_name='sriconfiguration',
            name='circuit_breaker_recovery_minutes',
            field=models.IntegerField(default=60, help_text='Minutes before circuit breaker resets after opening', verbose_name='circuit breaker recovery minutes'),
        ),
        migrations.AddField(
            model_name='sriconfiguration',
            name='circuit_breaker_threshold',
            field=models.IntegerField(default=5, help_text='Number of failures before circuit breaker opens', verbose_name='circuit breaker threshold'),
        ),
        migrations.AddField(
            model_name='sriconfiguration',
            name='cleanup_batch_size',
            field=models.IntegerField(default=100, help_text='Number of log entries to cleanup in each batch', verbose_name='cleanup batch size'),
        ),
        migrations.AddField(
            model_name='sriconfiguration',
            name='cleanup_days_threshold',
            field=models.IntegerField(default=90, help_text='Days after which logs are eligible for cleanup', verbose_name='cleanup days threshold'),
        ),
        migrations.AddField(
            model_name='sriconfiguration',
            name='compress_backup_files',
            field=models.BooleanField(default=True, help_text='Compress backup files to save storage space', verbose_name='compress backup files'),
        ),
        migrations.AddField(
            model_name='sriconfiguration',
            name='error_tracking',
            field=models.BooleanField(default=True, help_text='Track and analyze error patterns', verbose_name='error tracking'),
        ),
        migrations.AddField(
            model_name='sriconfiguration',
            name='max_retry_attempts',
            field=models.IntegerField(default=3, help_text='Maximum number of retry attempts', verbose_name='max retry attempts'),
        ),
        migrations.AddField(
            model_name='sriconfiguration',
            name='metrics_enabled',
            field=models.BooleanField(default=True, help_text='Enable metrics collection for SRI operations', verbose_name='metrics enabled'),
        ),
        migrations.AddField(
            model_name='sriconfiguration',
            name='notify_on_error',
            field=models.BooleanField(default=True, help_text='Send notification when document processing fails', verbose_name='notify on error'),
        ),
        migrations.AddField(
            model_name='sriconfiguration',
            name='notify_on_retry',
            field=models.BooleanField(default=False, help_text='Send notification when retrying failed document', verbose_name='notify on retry'),
        ),
        migrations.AddField(
            model_name='sriconfiguration',
            name='notify_on_success',
            field=models.BooleanField(default=True, help_text='Send notification when document is successfully authorized', verbose_name='notify on success'),
        ),
        migrations.AddField(
            model_name='sriconfiguration',
            name='performance_logging',
            field=models.BooleanField(default=True, help_text='Log performance metrics for SRI operations', verbose_name='performance logging'),
        ),
        migrations.AddField(
            model_name='sriconfiguration',
            name='pre_validation_enabled',
            field=models.BooleanField(default=True, help_text='Validate documents before sending to SRI', verbose_name='pre validation enabled'),
        ),
        migrations.AddField(
            model_name='sriconfiguration',
            name='queue_batch_timeout_minutes',
            field=models.IntegerField(default=5, help_text='Minutes to wait before processing incomplete batch', verbose_name='queue batch timeout minutes'),
        ),
        migrations.AddField(
            model_name='sriconfiguration',
            name='queue_max_size',
            field=models.IntegerField(default=1000, help_text='Maximum number of documents in processing queue', verbose_name='queue max size'),
        ),
        migrations.AddField(
            model_name='sriconfiguration',
            name='queue_processing_enabled',
            field=models.BooleanField(default=True, help_text='Enable queue-based batch processing', verbose_name='queue processing enabled'),
        ),
        migrations.AddField(
            model_name='sriconfiguration',
            name='retry_delay_minutes',
            field=models.IntegerField(default=5, help_text='Minutes to wait between retry attempts', verbose_name='retry delay minutes'),
        ),
        migrations.AddField(
            model_name='sriconfiguration',
            name='use_async_processing',
            field=models.BooleanField(default=True, help_text='Use background processing for SRI operations', verbose_name='use async processing'),
        ),
        migrations.AddField(
            model_name='sriconfiguration',
            name='validate_business_rules',
            field=models.BooleanField(default=True, help_text='Validate business rules before sending to SRI', verbose_name='validate business rules'),
        ),
        migrations.AddField(
            model_name='sriconfiguration',
            name='validate_xml_schema',
            field=models.BooleanField(default=True, help_text='Validate XML against SRI schema before sending', verbose_name='validate XML schema'),
        ),
        migrations.AddField(
            model_name='sriconfiguration',
            name='webhook_enabled',
            field=models.BooleanField(default=False, help_text='Enable webhook notifications for SRI events', verbose_name='webhook enabled'),
        ),
        migrations.AddField(
            model_name='sriconfiguration',
            name='webhook_secret',
            field=models.CharField(blank=True, help_text='Secret key for webhook authentication', max_length=255, verbose_name='webhook secret'),
        ),
        migrations.AddField(
            model_name='sriconfiguration',
            name='webhook_timeout_seconds',
            field=models.IntegerField(default=30, help_text='Timeout for webhook HTTP requests', verbose_name='webhook timeout seconds'),
        ),
        migrations.AddField(
            model_name='sriconfiguration',
            name='webhook_url',
            field=models.URLField(blank=True, help_text='URL to receive webhook notifications', verbose_name='webhook URL'),
        ),
    ]
