# Generated by Django 5.2.12 on 2026-03-29 05:34

import apps.sri_integration.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sri_integration', '0006_sriconfiguration_auto_backup_documents_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditnote',
            name='pdf_file',
            field=models.FileField(blank=True, upload_to=apps.sri_integration.models.get_sri_document_upload_path, verbose_name='PDF file'),
        ),
        migrations.AlterField(
            model_name='creditnote',
            name='signed_xml_file',
            field=models.FileField(blank=True, upload_to=apps.sri_integration.models.get_sri_document_upload_path, verbose_name='signed XML file'),
        ),
        migrations.AlterField(
            model_name='creditnote',
            name='xml_file',
            field=models.FileField(blank=True, upload_to=apps.sri_integration.models.get_sri_document_upload_path, verbose_name='XML file'),
        ),
        migrations.AlterField(
            model_name='debitnote',
            name='pdf_file',
            field=models.FileField(blank=True, upload_to=apps.sri_integration.models.get_sri_document_upload_path, verbose_name='PDF file'),
        ),
        migrations.AlterField(
            model_name='debitnote',
            name='signed_xml_file',
            field=models.FileField(blank=True, upload_to=apps.sri_integration.models.get_sri_document_upload_path, verbose_name='signed XML file'),
        ),
        migrations.AlterField(
            model_name='debitnote',
            name='xml_file',
            field=models.FileField(blank=True, upload_to=apps.sri_integration.models.get_sri_document_upload_path, verbose_name='XML file'),
        ),
        migrations.AlterField(
            model_name='electronicdocument',
            name='pdf_file',
            field=models.FileField(blank=True, upload_to=apps.sri_integration.models.get_sri_document_upload_path, verbose_name='PDF file'),
        ),
        migrations.AlterField(
            model_name='electronicdocument',
            name='signed_xml_file',
            field=models.FileField(blank=True, upload_to=apps.sri_integration.models.get_sri_document_upload_path, verbose_name='signed XML file'),
        ),
        migrations.AlterField(
            model_name='electronicdocument',
            name='xml_file',
            field=models.FileField(blank=True, upload_to=apps.sri_integration.models.get_sri_document_upload_path, verbose_name='XML file'),
        ),
        migrations.AlterField(
            model_name='purchasesettlement',
            name='pdf_file',
            field=models.FileField(blank=True, upload_to=apps.sri_integration.models.get_sri_document_upload_path, verbose_name='PDF file'),
        ),
        migrations.AlterField(
            model_name='purchasesettlement',
            name='signed_xml_file',
            field=models.FileField(blank=True, upload_to=apps.sri_integration.models.get_sri_document_upload_path, verbose_name='signed XML file'),
        ),
        migrations.AlterField(
            model_name='purchasesettlement',
            name='xml_file',
            field=models.FileField(blank=True, upload_to=apps.sri_integration.models.get_sri_document_upload_path, verbose_name='XML file'),
        ),
        migrations.AlterField(
            model_name='retention',
            name='pdf_file',
            field=models.FileField(blank=True, upload_to=apps.sri_integration.models.get_sri_document_upload_path, verbose_name='PDF file'),
        ),
        migrations.AlterField(
            model_name='retention',
            name='signed_xml_file',
            field=models.FileField(blank=True, upload_to=apps.sri_integration.models.get_sri_document_upload_path, verbose_name='signed XML file'),
        ),
        migrations.AlterField(
            model_name='retention',
            name='xml_file',
            field=models.FileField(blank=True, upload_to=apps.sri_integration.models.get_sri_document_upload_path, verbose_name='XML file'),
        ),
    ]
