# Generated by Django 5.2.13 on 2026-04-21 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sri_integration', '0007_alter_creditnote_pdf_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sriconfiguration',
            name='regimen',
            field=models.CharField(choices=[('GENERAL', 'Régimen General'), ('RIMPE_EMPRENDEDOR', 'Régimen RIMPE - Emprendedor'), ('RIMPE_POPULAR', 'Régimen RIMPE - Negocio Popular'), ('AGROPECUARIO', 'Régimen Agropecuario')], default='GENERAL', help_text='Tax regime for SRI documents', max_length=30, verbose_name='regimen'),
        ),
    ]
