# Generated by Django 6.0.3 on 2026-04-27 02:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sri_integration', '0008_sriconfiguration_regimen'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when the record was created.', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the record was last updated.', verbose_name='updated at')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this record should be treated as active.', verbose_name='is active')),
                ('payment_method_code', models.CharField(default='01', help_text='SRI Payment method code (e.g., 01 for Cash)', max_length=2, verbose_name='payment method code')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='amount')),
                ('payment_term', models.IntegerField(default=0, help_text='Term in units of time', verbose_name='payment term')),
                ('time_unit', models.CharField(default='dias', help_text='Unit of time for the term (e.g., dias)', max_length=20, verbose_name='time unit')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_methods', to='sri_integration.electronicdocument', verbose_name='document')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='updated by')),
            ],
            options={
                'verbose_name': 'Document Payment',
                'verbose_name_plural': 'Document Payments',
            },
        ),
    ]
