# Generated by Django 5.2.13 on 2026-04-27 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sri_integration', '0009_documentpayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditnote',
            name='email_sent',
            field=models.BooleanField(default=False, verbose_name='email sent'),
        ),
        migrations.AddField(
            model_name='creditnote',
            name='email_sent_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='email sent date'),
        ),
        migrations.AddField(
            model_name='creditnote',
            name='sri_response',
            field=models.JSONField(blank=True, default=dict, verbose_name='SRI response'),
        ),
        migrations.AddField(
            model_name='debitnote',
            name='email_sent',
            field=models.BooleanField(default=False, verbose_name='email sent'),
        ),
        migrations.AddField(
            model_name='debitnote',
            name='email_sent_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='email sent date'),
        ),
        migrations.AddField(
            model_name='debitnote',
            name='sri_response',
            field=models.JSONField(blank=True, default=dict, verbose_name='SRI response'),
        ),
        migrations.AddField(
            model_name='purchasesettlement',
            name='email_sent',
            field=models.BooleanField(default=False, verbose_name='email sent'),
        ),
        migrations.AddField(
            model_name='purchasesettlement',
            name='email_sent_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='email sent date'),
        ),
        migrations.AddField(
            model_name='purchasesettlement',
            name='sri_response',
            field=models.JSONField(blank=True, default=dict, verbose_name='SRI response'),
        ),
        migrations.AddField(
            model_name='retention',
            name='email_sent',
            field=models.BooleanField(default=False, verbose_name='email sent'),
        ),
        migrations.AddField(
            model_name='retention',
            name='email_sent_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='email sent date'),
        ),
        migrations.AddField(
            model_name='retention',
            name='sri_response',
            field=models.JSONField(blank=True, default=dict, verbose_name='SRI response'),
        ),
        migrations.AlterField(
            model_name='debitnote',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('GENERATED', 'Generated'), ('SIGNED', 'Signed'), ('SENT', 'Sent to SRI'), ('AUTHORIZED', 'Authorized'), ('REJECTED', 'Rejected'), ('ERROR', 'Error'), ('VOIDED', 'Voided')], default='DRAFT', max_length=20, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='electronicdocument',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('GENERATED', 'Generated'), ('SIGNED', 'Signed'), ('SENT', 'Sent to SRI'), ('AUTHORIZED', 'Authorized'), ('REJECTED', 'Rejected'), ('ERROR', 'Error'), ('VOIDED', 'Voided')], default='DRAFT', max_length=20, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='purchasesettlement',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('GENERATED', 'Generated'), ('SIGNED', 'Signed'), ('SENT', 'Sent to SRI'), ('AUTHORIZED', 'Authorized'), ('REJECTED', 'Rejected'), ('ERROR', 'Error'), ('VOIDED', 'Voided')], default='DRAFT', max_length=20, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='retention',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('GENERATED', 'Generated'), ('SIGNED', 'Signed'), ('SENT', 'Sent to SRI'), ('AUTHORIZED', 'Authorized'), ('REJECTED', 'Rejected'), ('ERROR', 'Error'), ('VOIDED', 'Voided')], default='DRAFT', max_length=20, verbose_name='status'),
        ),
    ]
