# Generated by Django 6.0.3 on 2026-04-27 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sri_integration', '0010_creditnote_email_sent_creditnote_email_sent_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditnote',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING', 'Pending'), ('GENERATED', 'Generated'), ('SIGNED', 'Signed'), ('SENT', 'Sent to SRI'), ('AUTHORIZED', 'Authorized'), ('REJECTED', 'Rejected'), ('ERROR', 'Error')], default='DRAFT', max_length=20, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='debitnote',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING', 'Pending'), ('GENERATED', 'Generated'), ('SIGNED', 'Signed'), ('SENT', 'Sent to SRI'), ('AUTHORIZED', 'Authorized'), ('REJECTED', 'Rejected'), ('ERROR', 'Error'), ('VOIDED', 'Voided')], default='DRAFT', max_length=20, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='electronicdocument',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING', 'Pending'), ('GENERATED', 'Generated'), ('SIGNED', 'Signed'), ('SENT', 'Sent to SRI'), ('AUTHORIZED', 'Authorized'), ('REJECTED', 'Rejected'), ('ERROR', 'Error'), ('VOIDED', 'Voided')], default='DRAFT', max_length=20, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='purchasesettlement',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING', 'Pending'), ('GENERATED', 'Generated'), ('SIGNED', 'Signed'), ('SENT', 'Sent to SRI'), ('AUTHORIZED', 'Authorized'), ('REJECTED', 'Rejected'), ('ERROR', 'Error'), ('VOIDED', 'Voided')], default='DRAFT', max_length=20, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='retention',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING', 'Pending'), ('GENERATED', 'Generated'), ('SIGNED', 'Signed'), ('SENT', 'Sent to SRI'), ('AUTHORIZED', 'Authorized'), ('REJECTED', 'Rejected'), ('ERROR', 'Error'), ('VOIDED', 'Voided')], default='DRAFT', max_length=20, verbose_name='status'),
        ),
    ]
