# Generated by Django 6.0.3 on 2026-05-01 02:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sri_integration', '0011_alter_creditnote_status_alter_debitnote_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentitem',
            name='credit_note',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sri_integration.creditnote', verbose_name='credit note'),
        ),
        migrations.AddField(
            model_name='documenttax',
            name='credit_note',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='taxes', to='sri_integration.creditnote', verbose_name='credit note'),
        ),
        migrations.AlterField(
            model_name='documentitem',
            name='document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sri_integration.electronicdocument', verbose_name='document'),
        ),
        migrations.AlterField(
            model_name='documenttax',
            name='document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='taxes', to='sri_integration.electronicdocument', verbose_name='document'),
        ),
    ]
