# Generated by Django 5.2.13 on 2026-05-04 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sri_integration', '0012_documentitem_credit_note_documenttax_credit_note_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debitnote',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING', 'Pending'), ('GENERATED', 'Generated'), ('SIGNED', 'Signed'), ('SENT', 'Sent to SRI'), ('AUTHORIZED', 'Authorized'), ('REJECTED', 'Rejected'), ('ERROR', 'Error'), ('VOIDED', 'Voided'), ('INTERNAL', 'Internal (No SRI)')], default='DRAFT', max_length=20, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='electronicdocument',
            name='access_key',
            field=models.CharField(blank=True, help_text='49-digit access key', max_length=49, null=True, unique=True, verbose_name='access key'),
        ),
        migrations.AlterField(
            model_name='electronicdocument',
            name='document_type',
            field=models.CharField(choices=[('INVOICE', 'Invoice'), ('CREDIT_NOTE', 'Credit Note'), ('DEBIT_NOTE', 'Debit Note'), ('RETENTION', 'Retention'), ('REMISSION_GUIDE', 'Remission Guide'), ('PURCHASE_SETTLEMENT', 'Purchase Settlement'), ('INTERNAL_NOTE', 'Internal Note (No SRI)')], max_length=20, verbose_name='document type'),
        ),
        migrations.AlterField(
            model_name='electronicdocument',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING', 'Pending'), ('GENERATED', 'Generated'), ('SIGNED', 'Signed'), ('SENT', 'Sent to SRI'), ('AUTHORIZED', 'Authorized'), ('REJECTED', 'Rejected'), ('ERROR', 'Error'), ('VOIDED', 'Voided'), ('INTERNAL', 'Internal (No SRI)')], default='DRAFT', max_length=20, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='purchasesettlement',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING', 'Pending'), ('GENERATED', 'Generated'), ('SIGNED', 'Signed'), ('SENT', 'Sent to SRI'), ('AUTHORIZED', 'Authorized'), ('REJECTED', 'Rejected'), ('ERROR', 'Error'), ('VOIDED', 'Voided'), ('INTERNAL', 'Internal (No SRI)')], default='DRAFT', max_length=20, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='retention',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING', 'Pending'), ('GENERATED', 'Generated'), ('SIGNED', 'Signed'), ('SENT', 'Sent to SRI'), ('AUTHORIZED', 'Authorized'), ('REJECTED', 'Rejected'), ('ERROR', 'Error'), ('VOIDED', 'Voided'), ('INTERNAL', 'Internal (No SRI)')], default='DRAFT', max_length=20, verbose_name='status'),
        ),
    ]
