# Generated by Django 5.2.3 on 2025-07-11 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ruc', models.CharField(help_text='RUC number (13 digits)', max_length=13, unique=True, verbose_name='RUC')),
                ('business_name', models.CharField(help_text='Official business name', max_length=300, verbose_name='business name')),
                ('trade_name', models.CharField(blank=True, help_text='Commercial or trade name', max_length=300, verbose_name='trade name')),
                ('email', models.EmailField(help_text='Main contact email', max_length=254, verbose_name='email')),
                ('phone', models.CharField(blank=True, help_text='Main contact phone', max_length=20, verbose_name='phone')),
                ('address', models.TextField(help_text='Complete business address', verbose_name='address')),
                ('is_active', models.BooleanField(default=True, help_text='Whether the company is active in the system', verbose_name='is active')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when the record was created.', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the record was last updated.', verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
                'ordering': ['business_name'],
            },
        ),
    ]
