# Generated by Django 5.2.3 on 2025-07-22 23:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyAPIToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text='Unique token for this company (auto-generated)', max_length=64, unique=True, verbose_name='Token Key')),
                ('name', models.CharField(help_text='Descriptive name for this token', max_length=100, verbose_name='Token Name')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this token is active and can be used', verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('can_create_documents', models.BooleanField(default=True, help_text='Permission to create SRI documents (invoices, etc.)', verbose_name='Can Create Documents')),
                ('can_read_documents', models.BooleanField(default=True, help_text='Permission to read/list SRI documents', verbose_name='Can Read Documents')),
                ('can_update_documents', models.BooleanField(default=False, help_text='Permission to update SRI documents', verbose_name='Can Update Documents')),
                ('can_delete_documents', models.BooleanField(default=False, help_text='Permission to delete SRI documents', verbose_name='Can Delete Documents')),
                ('can_manage_customers', models.BooleanField(default=True, help_text='Permission to create/edit customers', verbose_name='Can Manage Customers')),
                ('can_manage_products', models.BooleanField(default=True, help_text='Permission to create/edit products', verbose_name='Can Manage Products')),
                ('requests_per_hour', models.PositiveIntegerField(default=1000, help_text='Maximum number of API requests per hour', verbose_name='Requests Per Hour')),
                ('requests_per_day', models.PositiveIntegerField(default=10000, help_text='Maximum number of API requests per day', verbose_name='Requests Per Day')),
                ('total_requests', models.PositiveIntegerField(default=0, help_text='Total number of requests made with this token', verbose_name='Total Requests')),
                ('last_used_at', models.DateTimeField(blank=True, help_text='When this token was last used', null=True, verbose_name='Last Used At')),
                ('last_used_ip', models.GenericIPAddressField(blank=True, help_text='IP address of last request', null=True, verbose_name='Last Used IP')),
                ('expires_at', models.DateTimeField(blank=True, help_text='When this token expires (null = never expires)', null=True, verbose_name='Expires At')),
                ('company', models.OneToOneField(help_text='Company this token belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='api_token', to='companies.company', verbose_name='Company')),
            ],
            options={
                'verbose_name': 'Company API Token',
                'verbose_name_plural': 'Company API Tokens',
                'db_table': 'company_api_tokens',
                'ordering': ['-created_at'],
            },
        ),
    ]
