# Generated by Django 5.2.3 on 2025-07-23 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_companyapitoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='ambiente_sri',
            field=models.CharField(choices=[('1', 'Pruebas'), ('2', 'Producción')], default='1', help_text='Ambiente del SRI (1=Pruebas, 2=Producción)', max_length=1, verbose_name='ambiente SRI'),
        ),
        migrations.AddField(
            model_name='company',
            name='ciudad',
            field=models.CharField(blank=True, help_text='Ciudad de la empresa', max_length=100, verbose_name='ciudad'),
        ),
        migrations.AddField(
            model_name='company',
            name='codigo_establecimiento',
            field=models.CharField(default='001', help_text='Código del establecimiento (3 dígitos)', max_length=3, verbose_name='código establecimiento'),
        ),
        migrations.AddField(
            model_name='company',
            name='codigo_postal',
            field=models.CharField(blank=True, help_text='Código postal', max_length=10, verbose_name='código postal'),
        ),
        migrations.AddField(
            model_name='company',
            name='codigo_punto_emision',
            field=models.CharField(default='001', help_text='Código del punto de emisión (3 dígitos)', max_length=3, verbose_name='código punto emisión'),
        ),
        migrations.AddField(
            model_name='company',
            name='contribuyente_especial',
            field=models.CharField(blank=True, help_text='Número de contribuyente especial (si aplica)', max_length=5, null=True, verbose_name='contribuyente especial'),
        ),
        migrations.AddField(
            model_name='company',
            name='logo',
            field=models.ImageField(blank=True, help_text='Company logo for documents', null=True, upload_to='companies/logos/', verbose_name='logo'),
        ),
        migrations.AddField(
            model_name='company',
            name='obligado_contabilidad',
            field=models.CharField(choices=[('SI', 'Sí'), ('NO', 'No')], default='NO', help_text='Si está obligado a llevar contabilidad (crítico para SRI)', max_length=2, verbose_name='obligado a llevar contabilidad'),
        ),
        migrations.AddField(
            model_name='company',
            name='provincia',
            field=models.CharField(blank=True, help_text='Provincia de la empresa', max_length=100, verbose_name='provincia'),
        ),
        migrations.AddField(
            model_name='company',
            name='secuencial_factura',
            field=models.PositiveIntegerField(default=1, help_text='Próximo número secuencial para facturas', verbose_name='secuencial factura'),
        ),
        migrations.AddField(
            model_name='company',
            name='secuencial_nota_credito',
            field=models.PositiveIntegerField(default=1, help_text='Próximo número secuencial para notas de crédito', verbose_name='secuencial nota crédito'),
        ),
        migrations.AddField(
            model_name='company',
            name='secuencial_nota_debito',
            field=models.PositiveIntegerField(default=1, help_text='Próximo número secuencial para notas de débito', verbose_name='secuencial nota débito'),
        ),
        migrations.AddField(
            model_name='company',
            name='secuencial_retencion',
            field=models.PositiveIntegerField(default=1, help_text='Próximo número secuencial para retenciones', verbose_name='secuencial retención'),
        ),
        migrations.AddField(
            model_name='company',
            name='tipo_contribuyente',
            field=models.CharField(choices=[('PERSONA_NATURAL', 'Persona Natural'), ('EMPRESA_PRIVADA', 'Empresa Privada'), ('EMPRESA_PUBLICA', 'Empresa Pública'), ('ONG', 'Organización No Gubernamental'), ('OTRO', 'Otro')], default='PERSONA_NATURAL', help_text='Tipo de contribuyente según el SRI', max_length=20, verbose_name='tipo de contribuyente'),
        ),
        migrations.AddField(
            model_name='company',
            name='tipo_emision',
            field=models.CharField(choices=[('1', 'Normal'), ('2', 'Contingencia')], default='1', help_text='Tipo de emisión (1=Normal, 2=Contingencia)', max_length=1, verbose_name='tipo emisión'),
        ),
        migrations.AddField(
            model_name='company',
            name='website',
            field=models.URLField(blank=True, help_text='Company website', verbose_name='website'),
        ),
        migrations.AlterField(
            model_name='company',
            name='address',
            field=models.TextField(help_text='Complete business address (dirección matriz)', verbose_name='address'),
        ),
        migrations.AlterField(
            model_name='company',
            name='business_name',
            field=models.CharField(help_text='Official business name (Razón Social)', max_length=300, verbose_name='business name'),
        ),
        migrations.AlterField(
            model_name='company',
            name='trade_name',
            field=models.CharField(blank=True, help_text='Commercial or trade name (Nombre Comercial)', max_length=300, verbose_name='trade name'),
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['ruc'], name='companies_c_ruc_68064a_idx'),
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['is_active'], name='companies_c_is_acti_03043b_idx'),
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['tipo_contribuyente'], name='companies_c_tipo_co_4688a5_idx'),
        ),
    ]
