# Generated by Django 5.2.12 on 2026-03-29 05:34

import apps.companies.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_company_ambiente_sri_company_ciudad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.ImageField(blank=True, help_text='Company logo for documents', null=True, upload_to=apps.companies.models.company_logo_upload_path, verbose_name='logo'),
        ),
    ]
