# Generated by Django 5.2.12 on 2026-04-01 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_alter_company_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='plan',
            field=models.CharField(choices=[('basic', 'Básico'), ('professional', 'Profesional'), ('enterprise', 'Empresarial')], default='basic', help_text='Plan de facturación contratado', max_length=20, verbose_name='plan'),
        ),
    ]
