# Generated by Django 5.2.13 on 2026-04-21 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0005_company_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='regimen',
            field=models.CharField(choices=[('GENERAL', 'Régimen General'), ('RIMPE_EMPRENDEDOR', 'Régimen RIMPE - Emprendedor'), ('RIMPE_POPULAR', 'Régimen RIMPE - Negocio Popular'), ('AGROPECUARIO', 'Régimen Agropecuario')], default='GENERAL', help_text='Tipo de régimen tributario para impresión en facturas', max_length=30, verbose_name='régimen'),
        ),
    ]
