# Generated by Django 5.2.3 on 2025-07-11 18:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BackupConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when the record was created.', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the record was last updated.', verbose_name='updated at')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this record should be treated as active.', verbose_name='is active')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='backup name')),
                ('backup_type', models.CharField(choices=[('FULL', 'Full Backup'), ('INCREMENTAL', 'Incremental'), ('DIFFERENTIAL', 'Differential')], default='FULL', max_length=20, verbose_name='backup type')),
                ('frequency', models.CharField(choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly')], default='DAILY', max_length=20, verbose_name='frequency')),
                ('storage_type', models.CharField(choices=[('LOCAL', 'Local Storage'), ('S3', 'Amazon S3'), ('FTP', 'FTP Server'), ('SFTP', 'SFTP Server')], default='LOCAL', max_length=20, verbose_name='storage type')),
                ('storage_config', models.JSONField(default=dict, help_text='Storage-specific configuration (credentials, paths, etc.)', verbose_name='storage configuration')),
                ('retention_days', models.PositiveIntegerField(default=30, help_text='Number of days to keep backups', verbose_name='retention days')),
                ('max_backups', models.PositiveIntegerField(default=10, help_text='Maximum number of backups to keep', verbose_name='max backups')),
                ('include_media', models.BooleanField(default=True, verbose_name='include media files')),
                ('include_logs', models.BooleanField(default=False, verbose_name='include log files')),
                ('exclude_tables', models.JSONField(blank=True, default=list, help_text='Database tables to exclude from backup', verbose_name='exclude tables')),
                ('enabled', models.BooleanField(default=True, verbose_name='enabled')),
                ('last_backup', models.DateTimeField(blank=True, null=True, verbose_name='last backup')),
                ('last_backup_status', models.CharField(blank=True, choices=[('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('RUNNING', 'Running')], max_length=20, verbose_name='last backup status')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='updated by')),
            ],
            options={
                'verbose_name': 'Backup Configuration',
                'verbose_name_plural': 'Backup Configurations',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceMode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when the record was created.', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the record was last updated.', verbose_name='updated at')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this record should be treated as active.', verbose_name='is active')),
                ('is_enabled', models.BooleanField(default=False, verbose_name='maintenance mode enabled')),
                ('message', models.TextField(default='System is under maintenance. Please try again later.', help_text='Message to show users during maintenance', verbose_name='maintenance message')),
                ('allowed_ips', models.JSONField(blank=True, default=list, help_text='IP addresses that can access the system during maintenance', verbose_name='allowed IP addresses')),
                ('start_time', models.DateTimeField(blank=True, help_text='When maintenance mode was enabled', null=True, verbose_name='start time')),
                ('estimated_end_time', models.DateTimeField(blank=True, help_text='Estimated time when maintenance will be completed', null=True, verbose_name='estimated end time')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='updated by')),
            ],
            options={
                'verbose_name': 'Maintenance Mode',
                'verbose_name_plural': 'Maintenance Mode',
            },
        ),
        migrations.CreateModel(
            name='SystemSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when the record was created.', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the record was last updated.', verbose_name='updated at')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this record should be treated as active.', verbose_name='is active')),
                ('key', models.CharField(help_text='Unique identifier for this setting', max_length=100, unique=True, verbose_name='setting key')),
                ('value', models.TextField(help_text='Setting value', verbose_name='value')),
                ('default_value', models.TextField(blank=True, help_text='Default value for this setting', verbose_name='default value')),
                ('setting_type', models.CharField(choices=[('STRING', 'String'), ('INTEGER', 'Integer'), ('FLOAT', 'Float'), ('BOOLEAN', 'Boolean'), ('JSON', 'JSON'), ('EMAIL', 'Email'), ('URL', 'URL'), ('PASSWORD', 'Password')], default='STRING', max_length=20, verbose_name='setting type')),
                ('category', models.CharField(choices=[('SYSTEM', 'System'), ('EMAIL', 'Email'), ('SRI', 'SRI'), ('SECURITY', 'Security'), ('BACKUP', 'Backup'), ('NOTIFICATION', 'Notification'), ('INTEGRATION', 'Integration')], default='SYSTEM', max_length=20, verbose_name='category')),
                ('name', models.CharField(help_text='Human-readable name for this setting', max_length=100, verbose_name='display name')),
                ('description', models.TextField(blank=True, help_text='Description of what this setting does', verbose_name='description')),
                ('is_sensitive', models.BooleanField(default=False, help_text='Whether this setting contains sensitive information', verbose_name='is sensitive')),
                ('requires_restart', models.BooleanField(default=False, help_text='Whether changing this setting requires system restart', verbose_name='requires restart')),
                ('validation_regex', models.CharField(blank=True, help_text='Regular expression to validate the value', max_length=255, verbose_name='validation regex')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='updated by')),
            ],
            options={
                'verbose_name': 'System Setting',
                'verbose_name_plural': 'System Settings',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when the record was created.', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the record was last updated.', verbose_name='updated at')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this record should be treated as active.', verbose_name='is active')),
                ('theme', models.CharField(choices=[('LIGHT', 'Light'), ('DARK', 'Dark'), ('AUTO', 'Auto')], default='LIGHT', max_length=10, verbose_name='theme')),
                ('language', models.CharField(choices=[('es', 'Spanish'), ('en', 'English')], default='es', max_length=5, verbose_name='language')),
                ('dashboard_layout', models.JSONField(blank=True, default=dict, help_text='User dashboard layout configuration', verbose_name='dashboard layout')),
                ('email_notifications', models.BooleanField(default=True, help_text='Receive email notifications', verbose_name='email notifications')),
                ('browser_notifications', models.BooleanField(default=True, help_text='Receive browser notifications', verbose_name='browser notifications')),
                ('notification_frequency', models.CharField(choices=[('IMMEDIATE', 'Immediate'), ('HOURLY', 'Hourly'), ('DAILY', 'Daily'), ('WEEKLY', 'Weekly')], default='IMMEDIATE', max_length=20, verbose_name='notification frequency')),
                ('timezone', models.CharField(default='America/Guayaquil', help_text='User timezone', max_length=50, verbose_name='timezone')),
                ('items_per_page', models.PositiveIntegerField(default=20, help_text='Number of items to show per page in tables', verbose_name='items per page')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('default_company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_for_users', to='companies.company', verbose_name='default company')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='updated by')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'User Preference',
                'verbose_name_plural': 'User Preferences',
            },
        ),
        migrations.CreateModel(
            name='CompanySetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when the record was created.', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the record was last updated.', verbose_name='updated at')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this record should be treated as active.', verbose_name='is active')),
                ('key', models.CharField(help_text='Setting identifier', max_length=100, verbose_name='setting key')),
                ('value', models.TextField(help_text='Setting value', verbose_name='value')),
                ('setting_type', models.CharField(choices=[('STRING', 'String'), ('INTEGER', 'Integer'), ('FLOAT', 'Float'), ('BOOLEAN', 'Boolean'), ('JSON', 'JSON'), ('EMAIL', 'Email'), ('URL', 'URL'), ('PASSWORD', 'Password')], default='STRING', max_length=20, verbose_name='setting type')),
                ('name', models.CharField(max_length=100, verbose_name='display name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='companies.company', verbose_name='company')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='updated by')),
            ],
            options={
                'verbose_name': 'Company Setting',
                'verbose_name_plural': 'Company Settings',
                'ordering': ['company', 'name'],
                'unique_together': {('company', 'key')},
            },
        ),
    ]
