name: ruta_fact_movil
description: App móvil conectada al backend Django de RutaFact.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  flutter_dotenv: ^5.1.0
  file_selector_android: ^0.5.0+17
  intl: ^0.20.2
  web_socket_channel: ^3.0.1
  # 📍 GPS & Offline Tracking
  connectivity_plus: ^6.0.3
  path_provider: ^2.1.2
  flutter_map: ^6.1.0
  latlong2: ^0.9.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  geolocator: ^11.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - .env
